import { Team } from "./teamsData";

export const coreData: Team[] = [
  // ── Web Development Team (formerly Technical) ──────────────────────────────
  {
    id: "technical",
    label: "Web Development Team",
    members: [
      {
        id: "tc4",
        name: "Ronit Mahajan",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/DF-WZoSUdHIvdM0d_IMG_20260531_011912-RonitMahajan.jpg?auto=format,compress",
        github: "",
      },
      {
        id: "tc7",
        name: "Vidhyanshu Kumar",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/W5sKhmHh4OKXHrhg_Vidhyanshu.png?auto=format,compress",
        github: "",
      },
      {
        id: "tc5",
        name: "Samya Tiwari",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/p8V8Dsz7iqi-10sN_SamyaTiwari.PNG?auto=format,compress",
        github: "",
      },
      {
        id: "tc1",
        name: "Devishi Mathur",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/W5KRwRJVSw53gyda_DEVISHIMATHURTECHNICAL-DevishiMathur.jpeg?auto=format,compress",
        github: "",
      },
      {
        id: "tc2",
        name: "Divya Srivastava",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/hSABf85B-xIapdVX_DivyaSrivastava.png?auto=format,compress",
        github: "",
      },
      {
        id: "tc3",
        name: "Namit Tickoo",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/clq4Kstdx72XMT8l_8923D7CB-DA13-4B67-9B57-8EE83F4C50EB-NamitTickoo.jpeg?auto=format,compress",
        github: "",
      },
      {
        id: "tc8",
        name: "Aakanksha Kumar",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc9",
        name: "Arnav Srivastava",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc10",
        name: "Kavya Choudhary",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc11",
        name: "Kethan Anant",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc12",
        name: "Navya Goel",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc13",
        name: "Tanish Jain",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc14",
        name: "Aparna",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc15",
        name: "Aum Lenka",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc16",
        name: "Shaurya Saxena",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc17",
        name: "Aastha Sood",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc18",
        name: "Disha Bothra",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc19",
        name: "Mukti Dewnani",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc20",
        name: "Shlok Pandey",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc21",
        name: "Tanishq Bhatnagar",
        role: "Team Member",
        photo: null,
        github: "",
      },
    ],
  },

  // ── Graphic Design Team ───────────────────────────────────────────────────
  {
    id: "graphic-design",
    label: "Graphic Design Team",
    members: [
      {
        id: "gd1",
        name: "Aditi Bharadwaj",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd2",
        name: "Ananya Ghosh",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/3YkpwjioaTwU_mSK_AnanyaGhosh.jpg?auto=format,compress",
      },
      {
        id: "gd3",
        name: "Monishka Kanodia",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/B9WLZBdC-hyezZrx_IMG-20260529-WA0000-MonishkaKanodia.jpg?auto=format,compress",
      },
      {
        id: "gd4",
        name: "Nandini Khandelwal",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/Rf4-ssk4OQ6FERLf_IMG-20251010-WA0077~2-NandiniKhandelwal.jpg?auto=format,compress",
      },
      {
        id: "gd5",
        name: "Prakhar Raj",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd6",
        name: "Ruhaani Satija",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/ivpSrOCOF2Dp3ZJE_IMG-20260517-WA0090-1--RuhaaniSatija.jpg?auto=format,compress",
      },
      {
        id: "gd7",
        name: "Soham Prashant More",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/x1sj7zhtjJnjcO3e_IMG_20260201_155051-SohamMore.jpg?auto=format,compress",
      },
      {
        id: "gd8",
        name: "Ananya Srivastava",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd9",
        name: "Arunika",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd10",
        name: "Mit Parekh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd11",
        name: "Yuvraaj Dutta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd12",
        name: "Sahil",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd13",
        name: "Shivanshi Punj",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd14",
        name: "Vaani Dhiman",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd15",
        name: "Vidhi Makkar",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd16",
        name: "Maahi Arora",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd17",
        name: "Pranya Gupta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd18",
        name: "Sailendra Sesha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd19",
        name: "Vikram Khambra",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Curations Team ─────────────────────────────────────────────────────────
  {
    id: "curations",
    label: "Curations Team",
    members: [
      {
        id: "cu1",
        name: "Anchal Singh",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/F2JxaheCVkKMyRXq_IMG_5162~2-AnchalSingh.JPG?auto=format,compress",
        linkedin: "",
      },
      {
        id: "cu2",
        name: "Ankush Bhardwaj",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/8aGYurAtB-HzxwXG_IMG_20260530_184321-AnkushBhardwaj.jpg?auto=format,compress",
        linkedin: "",
      },
      {
        id: "cu3",
        name: "Atharv Vijayvergiya",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/wc-aSPUREmzR3P02_AtharvVijayvergiya.jpeg?auto=format,compress",
      },
      {
        id: "cu4",
        name: "Mishika Sehgal",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/xfcc8W6Btyz46zdo_MishikaSehgal.jpeg?auto=format,compress",
      },
      {
        id: "cu5",
        name: "Sanvi Sinha",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/979F0VCs9n5OJcXw_IMG_1937-SanviSinha.jpeg?auto=format,compress",
      },
      {
        id: "cu6",
        name: "Tejas Kaur",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu7",
        name: "Garvit Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu8",
        name: "Kanishk Punjabi",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu9",
        name: "Parth Gupta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu10",
        name: "Parth Santosh Bharati",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu11",
        name: "Alisha Chaudhary",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu12",
        name: "Nehal Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu13",
        name: "Saurish Mishra",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu14",
        name: "Aarav Goyal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu15",
        name: "Athana Sinha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu16",
        name: "Ayush Gupta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu17",
        name: "Shivansh Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu18",
        name: "Tanishka",
        role: "Team Member",
        photo: null,
      },

    ],
  },

  // ── Social Media Team ──────────────────────────────────────────────────────
  {
    id: "social-media",
    label: "Social Media Team",
    members: [
      {
        id: "sm1",
        name: "Aarohee Bharadwaj",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/aEkHe0rS3trf5ZHu_AaroheeBharadwaj.jpeg?auto=format,compress",
        linkedin: "",
      },
      {
        id: "sm2",
        name: "Adrit Das",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/myluYvyj7SlrEdnm_AdritDas.jpeg?auto=format,compress",
      },
      {
        id: "sm3",
        name: "Gunjita Saxena",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/QV5e-V5SM1V53MM9_8b55ae2e-426f-4d23-be7f-54de258af9a4-gunjitasaxena.jpeg?auto=format,compress",
      },
      {
        id: "sm4",
        name: "Naisha Mangla",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/6VJN8aKX8Mzb-_ag_IMG_5612-NaishaMangla.JPG?auto=format,compress",
      },
      {
        id: "sm5",
        name: "Saanvi Lepcha",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/PMi4cjmxObOOixlE_WhatsAppImage2026-06-01at9.07.08PM-SaanviLepcha.jpeg?auto=format,compress",
      },
      {
        id: "sm6",
        name: "Ankit Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm7",
        name: "Mohd Talha Sufyan",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm8",
        name: "Nileshwari Patil",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm9",
        name: "Snehreet Kaur",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm10",
        name: "Srshti Mehta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm11",
        name: "Suhana Verma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm12",
        name: "Anika Gujral",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm13",
        name: "Divya Sinha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm14",
        name: "Gaadha Amal Nair",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm15",
        name: "Ananya Khanna",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm16",
        name: "Ketan Kumar",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm17",
        name: "Ruchit Kumar Jha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm18",
        name: "Aanya Bharadwaj",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Media & Coverage Team ──────────────────────────────────────────────────
  {
    id: "media",
    label: "Media & Coverage Team",
    members: [
      {
        id: "mc1",
        name: "Aditya Raj",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/S5Q0v4yx9ZpL2yKH_IMG_20260531_014239-AdityaRaj.jpg?auto=format,compress",
        linkedin: "",
      },
      {
        id: "mc2",
        name: "Dwijesh Chilukuri",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/65379e8b-198c-4d7e-ad60-17873c088cf0_Dinesh+Yadav.jpg?auto=format,compress",
      },
      {
        id: "mc3",
        name: "Prakhar Gupta",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/vmzXOIhr0ms7RTP7_PrakharGupta.jpg?auto=format,compress",
      },
      {
        id: "mc4",
        name: "Riya Bisht",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/Kw69e8dP8pFMK490_IMG_20260531_235523-RiyaBisht.png?auto=format,compress",
      },
      {
        id: "mc5",
        name: "Hridey Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc6",
        name: "Prakhar Bansal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc7",
        name: "Sanya Varre",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc8",
        name: "Tamanna",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc9",
        name: "Tanishka Panda",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc10",
        name: "Yashika Agarwal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc11",
        name: "Yashu Pandey",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc12",
        name: "Shivi Srivastava",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc13",
        name: "Shubham Doshi",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc14",
        name: "Sugandh Gupta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc15",
        name: "Tirth patel",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Logistics Team ─────────────────────────────────────────────────────────
  {
    id: "logistics",
    label: "Logistics Team",
    members: [
      {
        id: "lo1",
        name: "Bhavya Chavan",
        role: "Team Member",
        photo: null,
        linkedin: "",
      },
      {
        id: "lo2",
        name: "Daksh Anand",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/y_3CLOo_q58rQwuL_DakshAnand.jpg?auto=format,compress",
      },
      {
        id: "lo3",
        name: "Shreet Sharma",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/HyWxjJQS45XnIdks_IMG_7076-ShreetSharma.jpeg?auto=format,compress",
      },
      {
        id: "lo4",
        name: "Taran Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo5",
        name: "Mohit Raj",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/ynTC43X5XyTGzCZu_MohitRaj.jpg?auto=format,compress",
      },
      {
        id: "lo6",
        name: "Pranjal",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/SmsfQEakBG7oAq5M_Pranjal_.png?auto=format,compress",
      },
      {
        id: "lo7",
        name: "Ashish Nath Jha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo8",
        name: "Avadhanula Pranav",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo9",
        name: "Harshish Kanoi",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo10",
        name: "Lakshya",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo11",
        name: "Mitul Arora",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo12",
        name: "Saksham Joshi",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo13",
        name: "Shaurya Pathak",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo14",
        name: "Vishwesh Gaidhani",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo15",
        name: "Yuvraj Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo16",
        name: "Arpit Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo17",
        name: "Atharv Garg",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo18",
        name: "Daksh Saxena",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo19",
        name: "Jayaditya De",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo20",
        name: "Keshav Bhatia",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo21",
        name: "Mehul Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo22",
        name: "Padhdar M. Mukeshbhai",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo23",
        name: "Saksham Verma",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Events Team ───────────────────────────────────────────────────────────
  {
    id: "events",
    label: "Events Team",
    members: [
      {
        id: "ev1",
        name: "Aarav Khurana",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/dnmdc9Dqolz0ZANs_IMG_0820_OriginalCopyCopy-AaravKhurana.jpeg?auto=format,compress",
        linkedin: "",
        github: "",
      },
      {
        id: "ev2",
        name: "Abir Harne",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/lxGHVqziI3jkdZ0U_IMG_8466-AbirHarne.jpeg?auto=format,compress",
        linkedin: "",
      },
      {
        id: "ev3",
        name: "Aditi Rai",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/8KRg0Sn5cYh0EIf2_df10e48a-6de9-4fb3-8ca7-8ded66189dd8-AditiRai.JPG?auto=format,compress",
      },
      {
        id: "ev4",
        name: "Amisha Upadhyay",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/IiLdU4CUn4UERb7U_AmishaUpadhyay.jpg?auto=format,compress",
      },
      {
        id: "ev5",
        name: "Ananya Mishra",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/t4T6eIJDnB4zNrXO_IMG_20260530_145430-AnanyaMishra.jpg?auto=format,compress",
      },
      {
        id: "ev6",
        name: "Anukriti Verma",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/YWHv3-hCCvBiCqGp_IMG-20260202-WA0018-AnukritiVerma.jpg?auto=format,compress",
      },
      {
        id: "ev7",
        name: "Harshvardhan Khaitan",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/ZGS110jvvgMDi4is_IMG_4006-HarshvardhanKhaitan.jpeg?auto=format,compress",
      },
      {
        id: "ev8",
        name: "Krishna Kakkar",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev9",
        name: "Pari Ahuja",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev10",
        name: "Prisha Mittal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev11",
        name: "Shreyansh Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev12",
        name: "Shriya Raizada",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev13",
        name: "Agrim Tripathi",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev14",
        name: "Aryan Wondraw",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev15",
        name: "Kyna Sehgal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev16",
        name: "Gargi Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev17",
        name: "Nishika Jain",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev18",
        name: "Pradyumna Raj Chaudhary",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev19",
        name: "Mehek Marwaha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev20",
        name: "Mohisha Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev21",
        name: "Nandini Bali",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev22",
        name: "Sahaj Bhattia",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev23",
        name: "Aditi Agarwal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev24",
        name: "Akshita Sinha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev25",
        name: "Ananya Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev26",
        name: "Krishna Tripathi",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev27",
        name: "Mahi Mehrotra",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev28",
        name: "Manya Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev29",
        name: "Niharika Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev30",
        name: "Aparna Anand",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev31",
        name: "Daksh Agarwal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev32",
        name: "Prannoy Sen",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev33",
        name: "Shreyansh Sinha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev34",
        name: "Sounarda Mondal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev35",
        name: "Swastika Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev36",
        name: "Tia Anuja",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev37",
        name: "Yash Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev38",
        name: "Yuvraj Sethi",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Marketing Team ────────────────────────────────────────────────────────
  {
    id: "marketing",
    label: "Marketing Team",
    members: [
      {
        id: "mk1",
        name: "Anvi Goyal",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/AJDF8V0Se74gTDYH_photo-output-AnviGoyal.jpeg?auto=format,compress",
        linkedin: "",
      },
      {
        id: "mk2",
        name: "Daksh",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/a7kHSyzkV8d_OdlO_594882BE-5946-4907-9F4E-2ABC0507E6F7-Daksh.png?auto=format,compress",
      },
      {
        id: "mk3",
        name: "Dhruv Talwar",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/bTy-ei28G9sImfcp_DhruvTalwar.jpg?auto=format,compress",
      },
      {
        id: "mk4",
        name: "Eva Singh",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/8VXNqjKeyhLyBAMW_IMG_5109-EvaSingh.jpeg?auto=format,compress",
      },
      {
        id: "mk5",
        name: "Kashvi Mohta",
        role: "Team Member",
        photo: null,
        linkedin: "",
      },
      {
        id: "mk6",
        name: "Shresht Gulati",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/Q6CZYFVzhSjSt5QK_IMG_9092-SRESHTHGULATI.jpeg?auto=format,compress",
      },
      {
        id: "mk7",
        name: "Srishti Suman Gupta",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/eS52X2-mXPcgdJmu_20260121_115421~3-SrishtiSumanGupta.jpg?auto=format,compress",
      },
      {
        id: "mk8",
        name: "Yuvika Sachdeva",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/YliS28QiWK7iz1cf_EEFF2AA5-7E99-4F7E-A340-98C3D1950904-YuvikaSachdeva.JPG?auto=format,compress",
      },
      {
        id: "mk9",
        name: "Adit Tandon",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk10",
        name: "Akshadha Gupta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk11",
        name: "Alisha Yadav",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk12",
        name: "Anshul Pandey",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk13",
        name: "Arnav Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk14",
        name: "Shriya Stuti",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk15",
        name: "Shriya Stutt",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk16",
        name: "Trishala Ojha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk17",
        name: "Abhigyan Padhy",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk18",
        name: "Abhishek Vishnoi",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk19",
        name: "Prarthana Agarwal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk20",
        name: "Shouryam Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk21",
        name: "Tanisha Salian",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk22",
        name: "Akansha Banerjee",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk23",
        name: "Arnav Meher",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk24",
        name: "Diwansh Khowala",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk25",
        name: "Priyanshu",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Corporate Team ────────────────────────────────────────────────────────
  {
    id: "corporate",
    label: "Corporate Team",
    members: [
      {
        id: "cp1",
        name: "Armaan Kashyap",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/SOT9Wpa23j7VmZNy_ArmaanKashyap.jpg?auto=format,compress",
        linkedin: "",
      },
      {
        id: "cp2",
        name: "Daksh Narwaria",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/rO5L7Q4UgAAKc492_IMG_20260531_131116-Daksh.jpg?auto=format,compress",
      },
      {
        id: "cp3",
        name: "Divya Surve",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/EBIwj0qfMrk4ZkRq_DivyaSurve.jpg?auto=format,compress",
      },
      {
        id: "cp4",
        name: "Krish Barnwal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp5",
        name: "Shana Srivastava",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp6",
        name: "Sweera Anand",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/QLqJaj_j-F4EIn2v_IMG_9434-SweeraAnand.jpeg?auto=format,compress",
      },
      {
        id: "cp7",
        name: "Amishi kingrani",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp8",
        name: "Atharva Awasthy",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp9",
        name: "Danish Mandalapu",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp10",
        name: "Harsh Wardhan",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp11",
        name: "Manasvi Karthik",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp12",
        name: "Neeyati Agrawal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp13",
        name: "Srisha Jha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp14",
        name: "Aanya Singhal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp15",
        name: "Saisha Narang",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp16",
        name: "Vaibhav Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp17",
        name: "Yash Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp18",
        name: "Akshita Rohilla",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp19",
        name: "Daksh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp20",
        name: "Jivaansh Chandna",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp21",
        name: "Shobham S. Panigarhy",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp22",
        name: "Vanshika Tyagi",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Hospitality Team ───────────────────────────────────────────────────────
  {
    id: "hospitality",
    label: "Hospitality Team",
    members: [
      {
        id: "ho1",
        name: "Arnav Khanna",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/arnav-khanna.avif",
        linkedin: "",
      },
      {
        id: "ho2",
        name: "Chaitanya Bharadwaj",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/chaitanya-bhardwaj.avif",
      },
      {
        id: "ho3",
        name: "Sanat Gupta",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/8tqn4fOm1Rq-L-tJ_40780-SanatGupta.png?auto=format,compress",
      },
      {
        id: "ho4",
        name: "Saanvi Mittal",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/ghe5Mec2Ib7L0WbF_SaanviMittal.jpg?auto=format,compress",
      },
      {
        id: "ho5",
        name: "Anshika Nagar",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho6",
        name: "Devangini",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho7",
        name: "Heet Bhatt",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho8",
        name: "Tushi Choudhary",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho9",
        name: "Arnav Asrani",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho10",
        name: "Naman Saini",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho11",
        name: "Ritesh Soni",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho12",
        name: "Aashi Gupta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho13",
        name: "Harsh Deep Ratna",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho14",
        name: "Prachi",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho15",
        name: "Veerottam K. Kulshrestha",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Content Team ──────────────────────────────────────────────────────────
  {
    id: "content",
    label: "Content Team",
    members: [
      {
        id: "co1",
        name: "Akshay Pathak",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/yj1sgPFIUwxUzqMA_IMG_9906-AkshayPathak.jpeg?auto=format,compress",
        linkedin: "",
      },
      {
        id: "co2",
        name: "Devika Beri",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/uZvbtP8Kb7HpmL92_IMG_20260530_212843-DevikaBeri.png?auto=format,compress",
      },
      {
        id: "co3",
        name: "Mehr Mehta",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/mehr-mehta.avif",
      },
      {
        id: "co4",
        name: "Rian Anand",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/mAyq2gIrQt-l3r7L_B1A19787-FC95-4FDD-BF68-4420D37560EB-RianAnand.png?auto=format,compress",
      },
      {
        id: "co5",
        name: "Rishita Malik",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/npcGJZJpNf4iqxGl_RishitaMalik.jpg?auto=format,compress",
      },
      {
        id: "co6",
        name: "Geetika Khatri",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co7",
        name: "Ipshita",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co8",
        name: "Lavisna Rohra",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co9",
        name: "Ananya Kedia",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co10",
        name: "Andrea Dia Benjamin",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co11",
        name: "Kavya Das",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co12",
        name: "Akshita Shah",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co13",
        name: "Anushka Soni",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co14",
        name: "Saloni Sinha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co15",
        name: "Vaibhav Verma",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Finance Team ──────────────────────────────────────────────────────────
  {
    id: "finance",
    label: "Finance Team",
    members: [
      {
        id: "fi1",
        name: "Anshul Sawhney",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/7Ar-mtj3touJ9FVE_IMG_1681-Anshulsawhney.jpeg?auto=format,compress",
        linkedin: "",
      },
      {
        id: "fi2",
        name: "Likisha Grover",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/VUMlwjNcI_IFXxJw_42B49845-51B3-4587-A1D3-D761DB3E23CE-LikishaGrover.jpeg?auto=format,compress",
      },
      {
        id: "fi3",
        name: "Tarush Prasad",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/iqh12zcQHmovzEf3_IMG_1076-TarushPrasad.jpeg?auto=format,compress",
      },
      {
        id: "fi4",
        name: "Navya Khurana",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi5",
        name: "Riddhi Gupta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi6",
        name: "Suyash K. Kshitij",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi7",
        name: "Dhruv Sahrawat",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi8",
        name: "Jannat Ghuman",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi9",
        name: "Raima",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi10",
        name: "Mansi Thakre",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi11",
        name: "Rachit Goyal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi12",
        name: "Suryansh Thakur",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi13",
        name: "Tansukh",
        role: "Team Member",
        photo: null,
      },
    ],
  },
    // ── Crafts Team ───────────────────────────────────────────────────────────
  {
    id: "crafts",
    label: "Crafts Team",
    members: [
      {
        id: "cr1",
        name: "Aarushi Gupta",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/5ElP1yb1z6lXsQqR_AarushiGupta.jpg?auto=format,compress",
        linkedin: "",
      },
      {
        id: "cr2",
        name: "Aashie Singh",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/aashie-singh.avif",
      },
      {
        id: "cr3",
        name: "Akshita Dhiman",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/p1YDObIKnRfCaWUf_IMG_8868-AkshitaDhiman.jpeg?auto=format,compress",
      },
      {
        id: "cr4",
        name: "Maya Jakhad",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/08KL4aNsgvnHGAjJ_IEEE-MayaJakhad.PNG?auto=format,compress",
        linkedin: "",
      },
      {
        id: "cr5",
        name: "Radhika Bansal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr6",
        name: "Anhad Ansari",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr7",
        name: "Ayaan Khan",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr8",
        name: "Kashvi Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr9",
        name: "Shubh Vats",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr10",
        name: "Zainab Israr",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr11",
        name: "Ifra Inam",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr12",
        name: "Kiana Agarwal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr13",
        name: "Spreha Verma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr14",
        name: "Tia Ahuja",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr15",
        name: "Ansh Gupta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr16",
        name: "Pratik Kaduskar",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr17",
        name: "Priyanshi Garg",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr18",
        name: "Vritika Trivedi",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Flying Squad ──────────────────────────────────────────────────────────
  {
    id: "flying-squad",
    label: "Flying Squad",
    members: [
      {
        id: "fs1",
        name: "Anirudh Rawat",
        role: "Team Member",
        photo: null,
        linkedin: "",
      },
      {
        id: "fs2",
        name: "Swapnil Srivastava",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fs3",
        name: "Garv Sharma",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/rfYmx8Csu3rfgoar_IMG_20260531_011152-GarvSharma.jpg?auto=format,compress",
      },
      {
        id: "fs4",
        name: "Rithik Masand",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fs5",
        name: "Armon Bhuyan",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fs6",
        name: "Arnav Yadav",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fs7",
        name: "Sarthak Sahay",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fs8",
        name: "Akshit Katare",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fs9",
        name: "Devang Garg",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fs10",
        name: "Prakhar Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fs11",
        name: "Medhansh",
        role: "Team Member",
        photo: null,
      },

    ],
  },
];
