import { Team } from "./teamsData";

export const coreData: Team[] = [
  // ── Web Development Team (formerly Technical) ──────────────────────────────
  {
    id: "technical",
    label: "Web Development Team",
    members: [
      {
        id: "tc4",
        name: "Ronit Mahajan",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/ronit-mahajan.avif",
        linkedin: "https://linkedin.com/in/ronit-mahajan",
        github: "",
      },
      {
        id: "tc7",
        name: "Vidhyanshu Kumar",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/vidhyanshu-kumar-cropped-v3-1781885800373.avif",
        linkedin: "https://www.linkedin.com/in/viidhyanshu/",
        github: "",
      },
      {
        id: "tc5",
        name: "Samya Tiwari",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/samya-tiwari.avif",
        linkedin: "https://www.linkedin.com/in/samyaa-tiwarii",
        github: "",
      },
      {
        id: "tc1",
        name: "Devishi Mathur",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/devishi-mathur.avif",
        linkedin: "https://www.linkedin.com/in/devishi-mathur-8380a3210/",
        github: "https://github.com/DevishiMathur",
      },
      {
        id: "tc2",
        name: "Divya Srivastava",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/divya-srivastava.avif",
        linkedin: "https://www.linkedin.com/in/divya-srivastava-363b383a0?trk=contact-info",
        github: "",
      },
      {
        id: "tc3",
        name: "Namit Tickoo",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/namit-tickoo.avif",
        linkedin: "https://www.linkedin.com/in/namit-tickoo-69b2a9367?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
        github: "",
      },
      {
        id: "tc8",
        name: "Aakanksha Kumar",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/KaI-Jh9PwEellx79_SeniorCoordinator_Technical%26Webdev_Aakanksha_Kumar.jpg?auto=format,compress",
        github: "",
      },
      {
        id: "tc9",
        name: "Tanish Jain",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/Cm-ZcAPvUPNhkJMK_Senior_Coordinator_Technical_Tanish-1-.jpeg?auto=format,compress",
        linkedin:"https://www.linkedin.com/in/tanishjain4004/",
        github: "https://github.com/TanishJain2006",
      },
      {
        id: "tc11",
        name: "Ketan Anant",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/Pckfv3lLN4u4Cxig_SC_Editorial_KetanAnant.jpg?auto=format,compree",
        github: "",
      },
      {
        id: "tc12",
        name: "Navya Goel",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/7s5ilhcplZJqIR_r_SeniorCordinator_SocialMedia_NavyaGoel.jpg?auto=format,compres",
        github: "",
      },
      {
        id: "tc13",
        name: "Arnav Srivastava",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/bvGQO_c-u-ULWfRZ_Joint_Head_Technical_Arnav.jpg?auto=format,compres",
        github: "",
      },
      {
        id: "tc14",
        name: "Aparna",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/Rf6P_ibkL7-m-V4C_AparnaMishra.jpg?auto=format,compress",
        github: "",
      },
      {
        id: "tc15",
        name: "Aum Lenka",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/1du2Z4QW10szME5o_AumLenka.jpeg?auto=format,compress",
        github: "",
      },
      {
        id: "tc16",
        name: "Shaurya Saxena",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/Vx7yQioXhh7x5jNd_ShauryaSaxena.jpg?auto=format,compress",
        github: "",
      },
      {
        id: "tc18",
        name: "Disha Bothra",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/KgA2HX5qFMt_ZROH_IMG-20260527-WA0004-DishaBothra.jpg?auto=format,compress",
        linkedin: "https://www.linkedin.com/in/disha-bothra-13562228b/",
        github: "https://github.com/dishab777",
      },
      {
        id: "tc19",
        name: "Mukti Dewnani",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/VfqrcA0vA0TGz0YM_MuktiDewnani.jpeg?auto=format,compress",
        linkedin: "https://www.linkedin.com/in/mukti-dewnani-92b12a305?utm_source=share_via&utm_content=profile&utm_medium=member_android",
        github: "https://github.com/dewnanimukti2007",
      },
      {
        id: "tc17",
        name: "Aastha Sood",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/foBaoShV4nSSMjb6_Screenshot_20260527_204028_Photos-AasthaSood.jpg?auto=format,compress",
        linkedin: "https://www.linkedin.com/in/aastha-sood-103bb337a",
        github: "",
      },
      {
        id: "tc21",
        name: "Tanishq Bhatnagar",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/wUrn19WQuKhi-ua5_OLA-TanishqB.jpeg?auto=format,compress",
        linkedin: "https://www.linkedin.com/in/tanishq-bhatnagar-2b9408349/",
        github: "https://github.com/TanishqBhatnagar312",
      },
    ],
  },

  // ── Graphic Design Team ───────────────────────────────────────────────────
  {
    id: "graphic-design",
    label: "Graphic Design Team",
    members: [
      {
        id: "gd1",
        name: "Aditi Bharadwaj",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/aditi-bhardwaj.avif",
        linkedin: "https://www.linkedin.com/in/aditibhardwaj12",
      },
      {
        id: "gd2",
        name: "Ananya Ghosh",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/ananya-ghosh.avif",
        linkedin: "https://www.linkedin.com/in/ananya-ghosh-a55a7531b/",
      },
      {
        id: "gd3",
        name: "Monishka Kanodia",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/monishka-kanodia.avif",
        linkedin: "https://www.linkedin.com/in/monishka-kanodia-71b757374?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      },
      {
        id: "gd4",
        name: "Nandini Khandelwal",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/nandini-khandelwal.avif",
        linkedin: "https://www.linkedin.com/in/nandinikhandelwasssl2007",
      },
      {
        id: "gd5",
        name: "Prakhar Raj",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd6",
        name: "Ruhaani Satija",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/ruhaani-satija.avif",
        linkedin: "https://www.linkedin.com/in/ruhaani-satija-044ab0385?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      },
      {
        id: "gd7",
        name: "Soham Prashant More",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/soham-prashant-more.avif",
        linkedin: "https://www.linkedin.com/in/soham-more-muj/",
      },
      {
        id: "gd8",
        name: "Ananya Srivastava",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/j2FTkMfbNfUbemco_Head_GraphicDesign_AnanyaSrivastav.png?auto=format,compres",
      },
      {
        id: "gd9",
        name: "Arunika",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/rC-iGpTv1cY8MM9o_Joint_Head_Graphic_Design_Arunika.png?auto=format,compres",
      },
      {
        id: "gd10",
        name: "Mit Parekh",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/Ag6pazrMlJuO7-qJ_Senoir.coordinator_GD_Mit.jpg?auto=format,compres",
      },
      {
        id: "gd11",
        name: "Yuvraaj Dutta",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/6h9SpvAuUnYD60u0_SeniorCoordinator_GraphicDesign_YuuvrajDutta.jpeg?auto=format,compres",
      },
      {
        id: "gd12",
        name: "Sahil",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/rnPwRYvMGv4tO4F0_SahilParashar.jpeg?auto=format,compress",
      },
      {
        id: "gd13",
        name: "Shivanshi Punj",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/oFEtomCBhQaYJvZR_shivanshipunj.jpeg?auto=format,compress",
      },
      {
        id: "gd14",
        name: "Vaani Dhiman",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/Ai1P-IC-v9SPDCH__Vaani.jpg?auto=format,compress",
      },
      {
        id: "gd15",
        name: "Vidhi Makkar",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/2UXlCsYbnXinkaVx_VidhiMakkar.jpeg?auto=format,compress",
      },
      {
        id: "gd16",
        name: "Maahi Arora",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/GGRfPp7fSFiTxqoZ_WhatsAppImage2026-05-29at1.58.29PM-MaahiArora.jpeg?auto=format,compress",
        linkedin: "https://www.linkedin.com/in/maahi-arora-4a6850378?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      },
      {
        id: "gd17",
        name: "Pranya Gupta",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/BvhATaPteU-v3Nea_PranyaGupta.jpg?auto=format,compress",
        linkedin: "https://www.linkedin.com/in/pranya-gupta-204684",
      },
      {
        id: "gd18",
        name: "Sailendra Sesha",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/DQ8p9MIGCEUuGCPY_SailendraPathiS.jpg?auto=format,compress",
        linkedin: "https://www.linkedin.com/in/sesha-sailendra-pathi",
      },
      {
        id: "gd19",
        name: "Vikram Khambra",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/0kvMWA_cON0aY6jj_VikramKhambra.jpeg?auto=format,compress",
        linkedin: "https://www.linkedin.com/in/vikram-khambra-826b633a3/",
      },
    ],
  },

  // ── Curations Team ─────────────────────────────────────────────────────────
  {
    id: "curations",
    label: "Curations Team",
    members: [
      {
        id: "cu1",
        name: "Anchal Singh",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/anchal-singh.avif",
        linkedin: "https://www.linkedin.com/in/anchal-singh-",
      },
      {
        id: "cu2",
        name: "Ankush Bhardwaj",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/ankush-bhardwaj.avif",
        linkedin: "https://www.linkedin.com/in/ankush-bhardwaj-b19621283",
      },
      {
        id: "cu3",
        name: "Atharv Vijayvergiya",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/atharv-vijayvergiya.avif",
        linkedin: "http://www.linkedin.com/in/atharv-vijayvergiya-91ab8a370",
      },
      {
        id: "cu4",
        name: "Mishika Sehgal",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/mishika-sehgal.avif",
        linkedin: "https://linkedin.com/in/mishika-sehgal-bb65ab363",
      },
      {
        id: "cu5",
        name: "Sanvi Sinha",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/sanvi-sinha.avif",
        linkedin: "https://www.linkedin.com/in/sanvi-sinha-24b167368/",
      },
      {
        id: "cu6",
        name: "Tejas Kaur",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/tejas-kaur.avif",
        linkedin: "https://www.linkedin.com/in/tejas-kaur-b793ba309/",
      },
      {
        id: "cu7",
        name: "Garvit Sharma",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/274TD5B-9Bt_7uBg_WhatsAppImage2026-08-04at23.38.54.jpeg?auto=format,compres",
      },
      {
        id: "cu8",
        name: "Kanishk Punjabi",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/A7aP5q5ojDCL-DmX_SeniorCoordinator_Curations_KanishkPunjabi.jpg?auto=format,compres",
      },
      {
        id: "cu9",
        name: "Parth Gupta",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/Ns09xWdaLg7F11YM_SeniorCoordinator_Curations_ParthGupta.png?auto=format,compres",
      },
      {
        id: "cu10",
        name: "Parth Santosh Bharati",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/PaI0kLmNmkTH0rOx_JointHead_Curations_ParthBharati.png?auto=format,compres",
      },
      {
        id: "cu11",
        name: "Alisha Chaudhary",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/nCZTbcuvw_DDo8Zb_AlishaChaudhary.jpg?auto=format,compress",
      },
      {
        id: "cu12",
        name: "Nehal Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu13",
        name: "Saurish Mishra",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/NbGt1OGgfFeNLM4G_SaurishMishra.jpg?auto=format,compress",
      },
      {
        id: "cu14",
        name: "Aarav Goyal",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/OtbfkIbvReSlt7oZ_AaravGoyal.jpg?auto=format,compress",
      },
      {
        id: "cu15",
        name: "Atharva Sinha",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/HRkKpmu1RDoF4WlU_AtharvaSinha.jpeg?auto=format,compress",
        linkedin: "https://www.linkedin.com/in/atharva-sinha-772436254/",
      },
      {
        id: "cu16",
        name: "Ayush Gupta",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/VzCXZiRavVQ7YGXP_IMG-20230628-WA0034-AyushGupta.jpg?auto=format,compress",
        linkedin: "https://www.linkedin.com/in/ayush-gupta-88a4b3373/",
      },
      {
        id: "cu17",
        name: "Shivansh Sharma",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/_2aTgpYHoNes_Gw3_IMG_1966-Gamingcentre2.jpeg?auto=format,compress",
        linkedin: "https://www.linkedin.com/in/shivansh-sharma-86309b378?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      },
      {
        id: "cu18",
        name: "Tanishka Bhatia",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/3mBiqyFmGotTFg30_TanishkaBhatia.jpg?auto=format,compress",
        photo: "https://images.prismic.io/ieeemuj/3mBiqyFmGotTFg30_TanishkaBhatia.jpg?auto=format,compress",
      },

    ],
  },

  // ── Social Media Team ──────────────────────────────────────────────────────
  {
    id: "social-media",
    label: "Social Media Team",
    members: [
      {
        id: "sm1",
        name: "Aarohee Bharadwaj",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/aarohee-bharadwaj.avif",
        linkedin: "https://www.linkedin.com/in/aaroheebharadwaj",
      },
      {
        id: "sm2",
        name: "Adrit Das",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/adrit-das.avif",
        linkedin: "https://www.linkedin.com/in/adrit-das-bb5194397?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      },
      {
        id: "sm3",
        name: "Gunjita Saxena",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/gunjita-saxena.avif",
        linkedin: "https://www.linkedin.com/in/gunjita-saxena-60bb17380?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      },
      {
        id: "sm4",
        name: "Naisha Mangla",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/naisha-mangla.avif",
        linkedin: "https://www.linkedin.com/in/naisha-mangla-1aa4a6280?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      },
      {
        id: "sm5",
        name: "Saanvi Lepcha",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/saanvi-lepcha.avif",
        linkedin: "https://www.linkedin.com/in/saanvi-lepcha-4a847a3b6",
      },
      {
        id: "sm6",
        name: "Ankit Sharma",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/T2_uqnYjWDGuhGq7_SeniorCoordinator_SM_AnkitSharma.webp?auto=format,compres",
      },
      {
        id: "sm7",
        name: "Mohd Talha Sufyan",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/0Q3Gf_URNPjxkRb6_0523fc4d04b0fbc33afc1ecb740c4b48dd85d1e7-2304x4096.avif?auto=format,compres",
      },
      {
        id: "sm8",
        name: "Nileshwari Patil",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/7VQ7TU56w0xSLp5w_JointHead_SocialMedia_NileshwariPatil.jpg?auto=format,compres",
      },
      {
        id: "sm9",
        name: "Snehreet Kaur",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/MKanEFJMdUWKTcnb_SeniorCoordinator_Media%26Coverage_SnehreetKaur.jpg?auto=format,compres",
      },
      {
        id: "sm10",
        name: "Srishti Mehta",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/jFp9frvCRhgakPKP_SeniorCoordinator_CommunityRelations_SrishtiMehta.jpeg?auto=format,compres",
      },
      {
        id: "sm11",
        name: "Suhana Verma",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/bTAXa9LBPn5g8ffs_HEAD_SOCIALMEDIA_SUHANAVERMA.jpeg?auto=format,compres",
      },
      {
        id: "sm12",
        name: "Ananya Khanna",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/O_vYMmFAN7BBcpD7_ANANYAKHANNA.jpg?auto=format,compres",
        linkedin: "https://www.linkedin.com/in/ananyakhanna2007?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      },
      {
        id: "sm13",
        name: "Divya Sinha",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/UdoPHUHsjKMl0Q0V_Divya.jpeg?auto=format,compress",
      },
      {
        id: "sm14",
        name: "Gaadha Amal Nair",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/Rg451cJWAlR12E2G_GaadhaAmalNair.jpeg?auto=format,compress",
      },
      {
        id: "sm15",
        name: "Anika Gujral",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm16",
        name: "Ketan Kumar",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/3taRXfNtM2616huR_IMG-20250724-WA0028-KetanKumar.jpg?auto=format,compress",
        linkedin: "https://www.linkedin.com/in/ketan-kumar-a6b06330b/",
      },
      {
        id: "sm17",
        name: "Ruchit Kumar Jha",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/cgEL_X-DOyhk-P-8_WhatsAppImage2026-06-01at1.38.27AM-RuchitJha.jpeg?auto=format,compress",
      },
      {
        id: "sm18",
        name: "Aanya Bharadwaj",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/aanya-bhardwaj.avif",
        linkedin: "https://www.linkedin.com/in/aanya-bhardwaj-a98b4536a?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      },
    ],
  },

  // ── Media & Coverage Team ──────────────────────────────────────────────────
  {
    id: "media",
    label: "Media & Coverage Team",
    members: [
      {
        id: "mc1",
        name: "Aditya Raj",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/aditya-raj.avif",
        linkedin: "https://www.linkedin.com/in/aditya-raj-aa8ab5397",
      },
      {
        id: "mc2",
        name: "Dwijesh Chilukuri",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/dwijesh-chilukuri.avif",
        linkedin: "https://www.linkedin.com/in/dwijesh-chilukuri-803177372?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      },
      {
        id: "mc3",
        name: "Prakhar Gupta",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/prakhar-gupta.avif",
        linkedin: "https://www.linkedin.com/in/prakharrdev",
      },
      {
        id: "mc4",
        name: "Riya Bisht",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/riya-bisht.avif",
        linkedin: "https://www.linkedin.com/in/riyabishtri",
      },
      {
        id: "mc5",
        name: "Hridey Singh",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/ETqWoN6pMRilgZwx_EA456E61-0FCD-4161-9F8B-C7BD6F12CB5B.JPG?auto=format,compres",
      },
      {
        id: "mc6",
        name: "Prakhar Bansal",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/XBMuiisJe2EeYxOQ_SeniorCoordinator_Media%26Coverage_Prakhar.png?auto=format,compres",
      },
      {
        id: "mc7",
        name: "Sanya Varre",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/O7hEGvMmn9KlD_Xx_SanyavarreJointheadmedia%26coverage.JPG?auto=format,compres",
      },
      {
        id: "mc8",
        name: "Tamanna",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/cmK6ODitfM13S1so_TamannaKinha.jpg?auto=format,compress",
      },
      {
        id: "mc9",
        name: "Tanishka Panda",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/UUaHoDp4rtwNwhxy_TanishkaPanda.jpeg?auto=format,compress",
      },
      {
        id: "mc10",
        name: "Yashika Agarwal",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/NULS-lKtHs2ohAFb_YashikaAgarwal.jpg?auto=format,compress",
      },
      {
        id: "mc11",
        name: "Yashu Pandey",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc12",
        name: "Shivi Srivastava",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/j5wX_d_rHQRryUEb_Screenshot_2026-05-30-22-13-35-14_99c04817c0de5652397fc8b56c3b3817-ShiviSrivastava.jpg?auto=format,compress",
        linkedin: "https://www.linkedin.com/in/shivi-srivastava-8b205b286?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: "mc13",
        name: "Shubham Doshi",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/W4nHPraluDgxRhlx_Screenshot2026-06-01at11.33.48PM-ShubhamDoshi.png?auto=format,compress",
        linkedin: "https://www.linkedin.com/in/shubham-doshi-a9863937a/",
      },
      {
        id: "mc14",
        name: "Sugandh Gupta",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/O25GiA5dgCg59SVz_SugandhGupta.jpg?auto=format,compress",
        linkedin: "https://www.linkedin.com/in/sugandh-gupta-9325a5357?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      },
      {
        id: "mc15",
        name: "Tirth patel",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/b6oO94SHPsEW21v4_IMG_8539-TirthPatel.png?auto=format,compress",
        linkedin: "https://www.linkedin.com/in/tirth-patel-329a2b374?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      },
    ],
  },

  // ── Logistics Team ─────────────────────────────────────────────────────────
  {
    id: "logistics",
    label: "Logistics Team",
    members: [
      {
        id: "lo1",
        name: "Bhavya Chavan",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/bhavya.avif",
        linkedin: "https://www.linkedin.com/in/bhavyachavan",
      },
      {
        id: "lo2",
        name: "Daksh Anand",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/daksh-anand.avif",
        linkedin: "https://www.linkedin.com/in/daksh-anand-870895412?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      },
      {
        id: "lo3",
        name: "Shreet Sharma",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/shreet-sharma.avif",
        linkedin: "https://www.linkedin.com/in/ShreetSharma",
      },
      {
        id: "lo4",
        name: "Taran Singh",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/taran-singh.avif",
        linkedin: "https://www.linkedin.com/in/taran-singh-b38a98320?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      },
      {
        id: "lo5",
        name: "Mohit Raj",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/mohit-raj.avif",
        linkedin: "https://www.linkedin.com/in/mohit-raj-006862412",
      },
      {
        id: "lo6",
        name: "Pranjal",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/pranjal.avif",
        linkedin: "https://www.linkedin.com/in/pranjal-muj",
      },
      {
        id: "lo7",
        name: "Ashish Nath Jha",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/KuZach94L_blszOF_JointHead_CommunityRelations_AshishNathJha.jpeg?auto=format,compres",
      },
      {
        id: "lo8",
        name: "Avadhanula Pranav",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/OQbJY2qwKc9QnkTW_SeniorCoordinator_Programs_PranavAvadhanula.jpeg?auto=format,compres",
      },
      {
        id: "lo9",
        name: "Harshish Kanoi",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo10",
        name: "Lakshya",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/Zc3UwuRnR8bDrgaL_Senior_Coordinator_Editorial_Lakshya.jpeg?auto=format,compres",
      },
      {
        id: "lo11",
        name: "Mitul Arora",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/sbHVxkW9CBCNNtke_SeniorCoordinator_Logistics_Mitul.png?auto=format,compres",
        linkedin: "",
      },
      {
        id: "lo12",
        name: "Saksham Joshi",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/VjnAmeuTilURBQyk_JointHead_Logistics_SakshamJoshi.jpg?auto=format,compres",
      },
      {
        id: "lo13",
        name: "Shaurya Pathak",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/VqibI9VcMvO83mb6_Senior_Coordinator_Logistics_Shaurya_Pathak.jpg?auto=format,compres",
      },
      {
        id: "lo14",
        name: "Vishwesh Gaidhani",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/GzQs_UxwgxjrQ8oa_Head_logistics_VishweshGaidhani.HEIC?auto=format,compres",
      },
      {
        id: "lo15",
        name: "Yuvraj Singh",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/HadU9HZgAFXMooWe_SeniorCoordinator_LogisticsYuvrajSingh.heif?auto=format,compres",
      },
      {
        id: "lo16",
        name: "Arpit Singh",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/PkVmepTJM5RPOyhP_ArpitSingh.jpg?auto=format,compress",
      },
      {
        id: "lo17",
        name: "Atharv Garg",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/GhyOinbVE9Rs-p9D_AtharvGarg.png?auto=format,compress",
      },
      {
        id: "lo18",
        name: "Daksh Saxena",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/ankXcnYJTtp0u88h_DakshSaxena.jpg?auto=format,compress",
      },
      {
        id: "lo19",
        name: "Jayaditya De",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/cv6sBg-HGmzhvEGf_IMG_20260528_182350-Jayaditya.jpg?auto=format,compress",
        linkedin: "https://www.linkedin.com/in/jayaditya-de-533509250/",
      },
      {
        id: "lo21",
        name: "Mehul Sharma",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/k_oglRPkxY2ULMtu_IMG_20260601_221023-MehulSharma.png?auto=format,compress",
      },
      {
        id: "lo22",
        name: "Padhdar M. Mukeshbhai",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/VzmNOlBhu1aK1c2I_MannPaghdar.jpg?auto=format,compress",
        linkedin: "https://www.linkedin.com/in/mann-paghdar-770046378?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      },
      {
        id: "lo23",
        name: "Saksham Verma",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/uOTUVdVHB6fzHHhb_IMG_20260530_220034100-Sakshamverma.jpg?auto=format,compress",
        linkedin: "https://www.linkedin.com/in/saksham-verma-071674393?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
    ],
  },

  // ── Events Team ───────────────────────────────────────────────────────────
  {
    id: "events",
    label: "Events Team",
    members: [
      {
        id: "ev1",
        name: "Aarav Khurana",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/aarav-khurana.avif",
        linkedin: "https://www.linkedin.com/in/aarav-khurana-6b5746373?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
        github: "",
      },
      {
        id: "ev2",
        name: "Abir Harne",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/abir-harne.avif",
        linkedin: "https://www.linkedin.com/in/abirharne",
      },
      {
        id: "ev3",
        name: "Aditi Rai",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/aditi-rai.avif",
        linkedin: "https://www.linkedin.com/in/aditi-rai-801832378/",
      },
      {
        id: "ev4",
        name: "Amisha Upadhyay",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/amisha-upadhyay.avif",
        linkedin: "https://www.linkedin.com/in/amisha-upadhyay-402796378?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      },
      {
        id: "ev5",
        name: "Ananya Mishra",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/ananya-mishra.avif",
        linkedin: "https://www.linkedin.com/in/ananya-mishra-87930a3a3/",
      },
      {
        id: "ev6",
        name: "Anukriti Verma",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/anukriti-verma.avif",
        linkedin: "https://www.linkedin.com/in/anukriti-verma-b3177a376/",
      },
      {
        id: "ev7",
        name: "Harshvardhan Khaitan",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/harshvardhan-khaitan.avif",
        linkedin: "https://www.linkedin.com/in/harshvardhankh",
      },
      {
        id: "ev8",
        name: "Krishna Kakkar",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev9",
        name: "Pari Ahuja",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/pari-ahuja.avif",
        linkedin: "https://www.linkedin.com/in/pari-ahuja-3550bb368",
      },
      {
        id: "ev10",
        name: "Prisha Mittal",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/prisha-mittal.avif",
        linkedin: "https://www.linkedin.com/in/prisha-mittal-561a33382?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      },
      {
        id: "ev11",
        name: "Shreyansh Sharma",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/shreyansh-sharma.avif",
        linkedin: "https://www.linkedin.com/in/shreyansh-sharma-97244726a/",
      },
      {
        id: "ev12",
        name: "Shriya Raizada",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/shriya-raizada.avif",
        linkedin: "http://linkedin.com/in/shriya-raizada-3b1420320",
      },
      {
        id: "ev13",
        name: "Agrim Tripathi",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/9PoWRzzOYOUAYqVX_SENIORCOORDINATOR_PROMOTIONS_AGRIMTRIPATHI.png?auto=format,compres",
      },
      {
        id: "ev14",
        name: "Aryan Wondraw",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/J9Huqy7Ak6Yr7EGF_JointHead_Corporate_AryanWondraw.jpg?auto=format,compres",
      },
      {
        id: "ev15",
        name: "Kyna Sehgal",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/Maq3dVGVWuCccPlu_SeniorCoordinator_CommunityRelations_KynaSehgal.jpg?auto=format,compres",
      },
      {
        id: "ev16",
        name: "Gargi Singh",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/xIvBy8AkC4WPxpp9_Seniorcoordinator_Programs_GargiSingh.HEIC?auto=format,compress",
      },
      {
        id: "ev17",
        name: "Nishika Jain",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/RyUpkP9G-9Nq0Ati_JointHead_Promotions_NishikaJain.jpg?auto=format,compres",
      },
      {
        id: "ev18",
        name: "Pradyumna Raj Chaudhary",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/pML4zaaf6mt35jXA_SeniorCoordinator_CommunityRelations_PradyumnaRajChaudhary_.jpg?auto=format,compres",
      },
      {
        id: "ev19",
        name: "Mehek Marwaha",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/FNX9CC9dCj8GF71U_MehekMarwaha.jpg?auto=format,compress",
      },
      {
        id: "ev20",
        name: "Mohisha Sharma",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/Lpt89Y5Kp_LXNoIc_Head_Programs_MohishaSharma.jpg?auto=format,compres",
      },
      {
        id: "ev21",
        name: "Nandini Bali",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/Uj7qKQBAtu8-IwB2_Seniorcoordinator_Programs_NandiniBali.jpg?auto=format,compres",
      },
      {
        id: "ev22",
        name: "Sahaj Bhatia",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/q4MJL6gibMfAZffG_JointHead_Programs_SahajBhatia.HEIC?auto=format,compres",
      },
      {
        id: "ev23",
        name: "Aditi Agarwal",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/iS81XGdunjEesfsn_Aditi.jpeg?auto=format,compress",
      },
      {
        id: "ev24",
        name: "Akshita Sinha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev25",
        name: "Ananya Singh",
        role: "Team Member",
        photo:"https://images.prismic.io/ieeemuj/9hCiPlg2vFC8rV1z_AnanyaSingh.jpeg?auto=format,compress",
      },
      {
        id: "ev26",
        name: "Krishna Tripathi",
        role: "Team Member",
        photo:"https://images.prismic.io/ieeemuj/eFiAXlVRrft9U6sx_KrishnaTripathi.jpg?auto=format,compress",
      },
      {
        id: "ev27",
        name: "Mahi Mehrotra",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/kcXxKFJ4QvZL_A88_MahiMehrotra.jpeg?auto=format,compress",
      },
      {
        id: "ev28",
        name: "Manya Singh",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/GJlDAknXzFSf0oRy_ManyaSingh.jpeg?auto=format,compress",
      },
      {
        id: "ev29",
        name: "Niharika Singh",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/Apqu-JClz1_m9kbR_Niharika.jpg?auto=format,compress",
      },
      {
        id: "ev30",
        name: "Aparna Anand",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/r7EIBEsyozw6HEpJ_IMG_2026-AparnaAnand.JPG?auto=format,compress",
      },
      {
        id: "ev31",
        name: "Daksh Agarwal",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/rSgZk7Sa1wwMQAsY_1-DakshAgarwal.jpg?auto=format,compress",
        linkedin: "https://www.linkedin.com/in/daksh-agarwal-546051378",
      },
      {
        id: "ev32",
        name: "Prannoy Sen",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/8v_IgM3KNZ9j09ak_3a3d186b-fbc5-4d26-8844-99175de31dbe-PrannoySen.png?auto=format,compress",
        linkedin: "https://www.linkedin.com/in/prannoy-sen-3aa64b3a0/",
      },
      {
        id: "ev33",
        name: "Shreyansh Sinha",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/dIkPusM5QkKyMQVx_ShreyanshSinha.png?auto=format,compress",
        linkedin: "https://www.linkedin.com/in/shreyansh-sinhaa/",
      },
      {
        id: "ev34",
        name: "Souharda Mondal",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/OxG0MnZmYt42aqOO_IMG_20260527_115623-SouhardaMondal.png?auto=format,compress",
      },
      {
        id: "ev35",
        name: "Swastika Singh",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/dUD6LClwysEcZ-it_SwastikaSingh.jpg?auto=format,compress",
        linkedin: "https://www.linkedin.com/in/swastika-singh-845152376",
      },
      {
        id: "ev36",
        name: "Tia Anuja",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/vScc7XFPR-guHH0S_IMG_4228-TiaAhuja.jpeg?auto=format,compress",
        linkedin: "https://www.linkedin.com/in/keshav-bhatia-42661a394?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      },
      {
        id: "ev37",
        name: "Yash Singh",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/Ln6R82C18EG5OfyG_YashSingh.jpeg?auto=format,compress",
      },
      {
        id: "ev38",
        name: "Yuvraj Sethi",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/Cfrheqs7KBdBuJhS_IMG_3734-YuvrajSethi.jpeg?auto=format,compress",
      },
    ],
  },

  // ── Marketing Team ────────────────────────────────────────────────────────
  {
    id: "marketing",
    label: "Marketing Team",
    members: [
      {
        id: "mk1",
        name: "Anvi Goyal",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/anvi-goyal.avif",
        linkedin: "https://www.linkedin.com/in/anvi-goyal-14796640b?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      },
      {
        id: "mk2",
        name: "Daksh",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/daksh.avif",
        linkedin: "",
      },
      {
        id: "mk3",
        name: "Dhruv Talwar",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/dhruv-talwar.avif",
        linkedin: "https://www.linkedin.com/in/dhruv-talwar-4015872a1",
      },
      {
        id: "mk4",
        name: "Eva Singh",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/eva.avif",
        linkedin: "https://www.linkedin.com/in/eva-singh-96852a29b/",
      },
      {
        id: "mk5",
        name: "Kashvi Mohta",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/kashvi-mohta.avif",
        linkedin: "https://www.linkedin.com/in/kashvi-mohta-73a516378",
      },
      {
        id: "mk6",
        name: "Shresht Gulati",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/shresth-gulati.avif",
        linkedin: "https://www.linkedin.com/in/shresth-gulati-00a029333?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      },
      {
        id: "mk7",
        name: "Srishti Suman Gupta",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/srishti-suman-gupta.avif",
        linkedin: "https://www.linkedin.com/in/srishti-suman-g-820005383?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      },
      {
        id: "mk8",
        name: "Yuvika Sachdeva",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/yuvika-sachdeva.avif",
        linkedin: "https://www.linkedin.com/in/yuvika-sachdeva-82a391295?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      },
      {
        id: "mk9",
        name: "Adit Tandon",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/vdVSVNYBidVVGd_1_Seniorcoordinator_promotions_AditTandon.dng?auto=format,compres",
      },
      {
        id: "mk10",
        name: "Akshadha Gupta",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/RnV1mM-AXknYmmGg_JOINTHEAD_CREATIVEASSETS_AKSHADHAGUPTA.jpg?auto=format,compres",
      },
      {
        id: "mk11",
        name: "Alisha Yadav",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/BqbH1RMFifdCvhaX_Seniorcoordinator_promotions_Alisha.heif?auto=format,compres",
      },
      {
        id: "mk12",
        name: "Anshul Pandey",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/s5ZE1iicf_IyrH0M_SeniorCoordinator_CreativeAssetsandInventory_AnshulPandey.jpg?auto=format,compres",
      },
      {
        id: "mk13",
        name: "Arnav Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk14",
        name: "Shriya Stuti",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/eta1flztTHi3SdR0_70b15c27601f0dc4f918ceb038b0786801d5f01c-3024x4032.jpg?auto=format,compres",
      },
      {
        id: "mk15",
        name: "Shriya Stutt",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/eta1flztTHi3SdR0_70b15c27601f0dc4f918ceb038b0786801d5f01c-3024x4032.jpg?auto=format,compres",
      },
      {
        id: "mk16",
        name: "Trishala Ojha",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/41jNLV1lD_trY4WF_SeniorCoordinator_SocialMedia_TrishalaOjha.jpg?auto=format,compres",
      },
      {
        id: "mk17",
        name: "Abhigyan Padhy",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/4ERUzj1l2qkI2dz4_AbhigyanPadhy.jpeg?auto=format,compress",
      },
      {
        id: "mk18",
        name: "Abhishek Vishnoi",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/NGvNFtpYkHE13JUs_AbhishekVishnoi.jpeg?auto=format,compress",
      },
      {
        id: "mk19",
        name: "Prarthana Agarwal",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/ThHwKNM1wNygsN2A_PrarthanaAgarwal.jpg?auto=format,compress",
      },
      {
        id: "mk20",
        name: "Shouryam Sharma",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/15QEiMdDZBjVTQQh_ShouryamSharma.jpeg?auto=format,compress",
      },
      {
        id: "mk21",
        name: "Tanisha Salian",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/-vrRd44S5KhG8ycK_TanishaSalian.jpg?auto=format,compress",
      },
      {
        id: "mk22",
        name: "Akanksha Banerjee",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/ec1xXJz9Iat88yNT_IMG_9157-AKANKSHABANERJEE.jpeg?auto=format,compress",
        linkedin: "",
      },
      {
        id: "mk24",
        name: "Divyansh Khowala",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/SXwy2qcLCdWkUlkY_CIS-DivyanshKhowala.jpeg?auto=format,compress",
        linkedin: "",
      },
    ],
  },

  // ── Corporate Team ────────────────────────────────────────────────────────
  {
    id: "corporate",
    label: "Corporate Team",
    members: [
      {
        id: "cp1",
        name: "Armaan Kashyap",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/armaan-kashyap.avif",
        linkedin: "https://www.linkedin.com/in/armaan-kashyap-46a594371",
      },
      {
        id: "cp2",
        name: "Daksh Narwaria",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/daksh-narwaria.avif",
        linkedin: "https://www.linkedin.com/in/dakshnarwaria?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      },
      {
        id: "cp3",
        name: "Divya Surve",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/divya-surve.avif",
        linkedin: "https://www.linkedin.com/in/divya-surve-30797036b/",
      },
      {
        id: "cp4",
        name: "Krish Barnwal",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/krish-barnwal.avif",
        linkedin: "https://www.linkedin.com/in/krish-b-2b33b829a?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      },
      {
        id: "cp5",
        name: "Shana Srivastava",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/shana-srivastava.avif",
        linkedin: "https://www.linkedin.com/in/shana-srivastava-489a81366",
      },
      {
        id: "cp6",
        name: "Sweera Anand",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/sweera-anand.avif",
        linkedin: "",
      },
      {
        id: "cp7",
        name: "Amishi kingrani",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/5yPe5dbITEc8aejI_SeniorCoordinator_Editorial_AmishiKingrani.jpg?auto=format,compres",
      },
      {
        id: "cp8",
        name: "Atharva Awasthy",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/L3ZaIqrseAu4B_6F_SeniorCoordinator_CorporateAffairs_AtharvaAwasthy.jpg?auto=format,compres",
      },
      {
        id: "cp9",
        name: "Danish Mandalapu",
        role: "Team Member",
        photo:"https://images.prismic.io/ieeemuj/UvU9p09z_dkGEfsZ_SeniorCoordinator_CorporateAffairs_DanishMandalapu.png?auto=format,compress",
      },
      {
        id: "cp10",
        name: "Harsh Wardhan",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/ooKFDovKL7sCVfgO_Head_Curations_Harshwardhan.png?auto=format,compres",
      },
      {
        id: "cp11",
        name: "Manasvi Karthik",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/0_Z1T35kJRzCvGZJ_Head_CorporateAffairs_ManasviKarthik_.jpg?auto=format,compres",
      },
      {
        id: "cp12",
        name: "Neeyati Agrawal",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/-YXxabmccIp4lWrX_Head_Communityrelations_NeeyatiAgrawal.jpg?auto=format,compres",
      },
      {
        id: "cp13",
        name: "Srisha Jha",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/qahflpDmShtHgg57_SeniorCoordinator_SocialMedia_SrishaJha.jpg?auto=format,compres",
      },
      {
        id: "cp14",
        name: "Aanya Singhal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp15",
        name: "Saisha Narang",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/3TLupfQCxOYNjIpi_SaishaNarang.jpg?auto=format,compress",
      },
      {
        id: "cp16",
        name: "Vaibhav Sharma",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/KVy_GYLgLUI7PqVI_VaibhavSharma.jpg?auto=format,compress",
      },
      {
        id: "cp17",
        name: "Yash Sharma",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/gfCs0oc4HQ2TkjvG_YashSharma.jpg?auto=format,compress",
      },
      {
        id: "cp19",
        name: "Daksh Bhardwaj",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/ECg2mhbUdLsWYqaY_daksh-DakshBhardwaj.jpeg?auto=format,compress",
        linkedin: "",
      },
      {
        id: "cp20",
        name: "Jivaansh Chandna",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/TuS00YKbwXVbvzkX_IMG_0914-JivaanshChandna.jpeg?auto=format,compress",
        linkedin: "",
      },
      {
        id: "cp21",
        name: "Shobhan S. Panigarhy",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/OkLnSZ8oMgJlnZOr_20260527_004125-ShobhanSidharth.JPG?auto=format,compress",
        linkedin: "",
      },
      {
        id: "cp22",
        name: "Vanshika Tyagi",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/4J0mnOhjAMR3Oarw_VanshikaTyagi.png?auto=format,compress",
        linkedin: "",
      },
    ],
  },

  // ── Hospitality Team ───────────────────────────────────────────────────────
  {
    id: "hospitality",
    label: "Hospitality Team",
    members: [
      {
        id: "ho1",
        name: "Arnav Khanna",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/arnav-khanna.avif",
        linkedin: "https://www.linkedin.com/in/arnav-khanna-655113381",
      },
      {
        id: "ho2",
        name: "Chaitanya Bharadwaj",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/chaitanya-bhardwaj.avif",
        linkedin: "https://www.linkedin.com/in/chaitanya-bhardwaj-1a1a81372/",
      },
      {
        id: "ho3",
        name: "Sanat Gupta",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/sanat-gupta.avif",
        linkedin: "https://www.linkedin.com/in/sanat-g-b51701249",
      },
      {
        id: "ho4",
        name: "Saanvi Mittal",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/saanvi-mittal.avif",
        linkedin: "https://www.linkedin.com/in/saanvi-m-362905353?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
      },
      {
        id: "ho5",
        name: "Anshika Nagar",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/bk2nzhdDroAEinYy_Seniorcoordinator_Promotions_Anshikanagar.png?auto=format,compres",
        linkedin: "",
      },
      {
        id: "ho6",
        name: "Devangini",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/PifYQblPLhdL1e_J_SeniorCoordinator_CreativeAssetsandManagement_Devangini.jpg?auto=format,compres",
      },
      {
        id: "ho7",
        name: "Heet Bhatt",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/ukU578lo0D6bE2VQ_SC_Logistics_Heetbhatt.jpg?auto=format,compres",
      },
      {
        id: "ho8",
        name: "Tushi Choudhary",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho9",
        name: "Arnav Asrani",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho10",
        name: "Naman Saini",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/qspswDzrscWB9a_B_NamanSaini.jpeg?auto=format,compress",
      },
      {
        id: "ho11",
        name: "Ritesh Soni",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/EFZiSp0GPF8Bg8Z__Ritesh.jpg?auto=format,compress",
      },
      {
        id: "ho12",
        name: "Aashi Gupta",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/-7O0w4BCXAhjywpq_AashiGupta.jpg?auto=format,compress",
      },
      {
        id: "ho13",
        name: "Harsh Deep Ratna",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/qFXuhmeV6XY-pBrS_Harsh.jpg?auto=format,compress",
      },
      {
        id: "ho14",
        name: "Prachi",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho15",
        name: "Veerottam K. Kulshrestha",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/lIT6rOpMrRTvlU1u__DSC0924-VeerottamKulshrestha.jpg?auto=format,compress",
        linkedin: "",
      },
    ],
  },

  // ── Content Team ──────────────────────────────────────────────────────────
  {
    id: "content",
    label: "Content Team",
    members: [
      {
        id: "co1",
        name: "Akshay Pathak",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/akshay-pathak.avif",
        linkedin: "https://www.linkedin.com/in/akshay-pathak-b72576362?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      },
      {
        id: "co2",
        name: "Devika Beri",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/devika-beri.avif",
        linkedin: "https://www.linkedin.com/in/devika-beri-",
      },
      {
        id: "co3",
        name: "Mehr Mehta",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/mehr-mehta.avif",
        linkedin: "https://www.linkedin.com/in/mehr-mehta-986598376?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
      },
      {
        id: "co4",
        name: "Rian Anand",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/rian-anand.avif",
        linkedin: "https://www.linkedin.com/in/riananand",
      },
      {
        id: "co5",
        name: "Rishita Malik",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/rishita-malik.avif",
        linkedin: "https://www.linkedin.com/in/rishita-malik-91005136b",
      },
      {
        id: "co6",
        name: "Geetika Khatri",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/KE091SivEarkMbWa_Head_Editorial_GeetikaKhatri.jpg?auto=format,compres",
      },
      {
        id: "co7",
        name: "Ipsita Prabhakar",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/vt5qZCxKXHroCvz7_SeniorCoordinator_CreativeAssetsandInventory_IpsitaPrabhakar_.jpg?auto=format,compress",
      },
      {
        id: "co8",
        name: "Lavisha Rohra",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/63AVTBlEEne1AvVt_seniorcoordinator_editorial_LavishaRohra.jpeg?auto=format,compres",
      },
      {
        id: "co9",
        name: "Ananya Kedia",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/4Pm0K9gZNPvsB5oE_AnanyaKedia.jpg?auto=format,compress",
      },
      {
        id: "co10",
        name: "Andrea Dia Benjamin",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/XqSjDybomWQbq2y__AndreaBenjamin.jpeg?auto=format,compress",
      },
      {
        id: "co11",
        name: "Kavya Das",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/Pay8h8ycLwqc4wSi_KavyaDas.jpg?auto=format,compress",
      },
      {
        id: "co12",
        name: "Akshita Shah",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/-h3Ya0CYgg3Yf-M-_IMG_9965-AkshitaShah.jpeg?auto=format,compress",
        linkedin: "https://www.linkedin.com/in/akshitashah12/",
      },
      {
        id: "co14",
        name: "Saloni Sinha",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/g8S2XMvQxARrTVeM_SaloniSinha.jpg?auto=format,compress",
        linkedin: "",
      },
      {
        id: "co15",
        name: "Vaibhav Verma",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/YOSoc8hq9qcvpgT9_IMG_20260531_175310598_HDR-VaibhavVerma.jpg?auto=format,compress",
        linkedin: "",
      },
    ],
  },

  // ── Finance Team ──────────────────────────────────────────────────────────
  {
    id: "finance",
    label: "Finance Team",
    members: [
      {
        id: "fi1",
        name: "Anshul Sawhney",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/anshul-sawhney.avif",
        linkedin: "https://www.linkedin.com/in/anshul-sawhney-280263370?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      },
      {
        id: "fi2",
        name: "Likisha Grover",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/likisha.avif",
        linkedin: "https://www.linkedin.com/in/likisha-grover-b602ab379/",
      },
      {
        id: "fi3",
        name: "Tarush Prasad",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/tarush-prasad.avif",
        linkedin: "https://www.linkedin.com/in/tarush-prasad-834b64380/",
      },
      {
        id: "fi4",
        name: "Navya Khurana",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/EtDdnaaiIk8WQbBV_Seniorcoordinator_curation_NavyaKhurana.jpeg?auto=format,compress",
      },
      {
        id: "fi5",
        name: "Riddhi Gupta",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/fNqKMK9n9hW_K5fJ_SeniorCoordinator_CommunityRelations_RiddhiGupta.jpg?auto=format,compres",
      },
      {
        id: "fi6",
        name: "Suyash K. Kshitij",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/nOFiizWwt4DTyFjL_SeniorCoordinatorGraphicDesignSuyashKarnKshitij.jpeg?auto=format,compres",
      },
      {
        id: "fi7",
        name: "Dhruv Sahrawat",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/qVQ6npV4eQkNtR_u_DhruvSahrawat.jpeg?auto=format,compress",
      },
      {
        id: "fi8",
        name: "Jannat Ghuman",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/snfOwlXv8708R-qN_JannatGhuman.jpeg?auto=format,compress",
      },
      {
        id: "fi9",
        name: "Raima",
        role: "Team Member",
        photo:"https://images.prismic.io/ieeemuj/anIzqx38J4rhx7ci_RaimaAli.jpeg?auto=format,compress",
      },
      {
        id: "fi10",
        name: "Mansi Thakre",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/JbeUgHLHzUt72CfT_mansiphoto-MansiThakre.jpg?auto=format,compress",
        linkedin: "",
      },
      {
        id: "fi11",
        name: "Rachit Goyal",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/SVPe_MhQvVg3TCxc_WhatsAppImage2026-05-27at1.06.08AM-RachitGoyal.jpeg?auto=format,compress",
        linkedin: "",
      },
      {
        id: "fi12",
        name: "Suryansh Thakur",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/4w3VzR1AmiiPXOsw_SuryanshThakur.jpeg?auto=format,compress",
        linkedin: "",
      },
      {
        id: "fi13",
        name: "Tansukh Goyal",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/TM5cicvOZpTQTq1N_TANSUKHGOYAL.jpg?auto=format,compress",
        linkedin: "",
      },
    ],
  },
    // ── Crafts Team ───────────────────────────────────────────────────────────
  {
    id: "crafts",
    label: "Crafts Team",
    members: [
      {
        id: "cr1",
        name: "Aarushi Gupta",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/aarushi-gupta.avif",
        linkedin: "https://www.linkedin.com/in/aarushi-gupta",
      },
      {
        id: "cr2",
        name: "Aashie Singh",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/aashie-singh.avif",
        linkedin: "https://www.linkedin.com/in/aashie-singh-50393237b?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      },
      {
        id: "cr3",
        name: "Akshita Dhiman",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/akshita-dhiman.avif",
        linkedin: "https://www.linkedin.com/in/akshita-dhiman-29630a343",
      },
      {
        id: "cr4",
        name: "Maya Jakhad",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/maya-jakhad.avif",
        linkedin: "https://www.linkedin.com/in/maya-jakhad-43a459379?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      },
      {
        id: "cr5",
        name: "Radhika Bansal",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/radhika.avif",
        linkedin: "https://www.linkedin.com/in/radhika-bansal-3b4849412",
      },
      {
        id: "cr6",
        name: "Anhad Ansari",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/_OBh1kjrdq8ZtkEv_Head_CreativeAssetsAndInventory_AnhadAnsari.jpg?auto=format,compres",
      },
      {
        id: "cr7",
        name: "Ayaan Khan",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr8",
        name: "Kashvi Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr9",
        name: "Shubh Vats",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr10",
        name: "Zainab Israr",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/cmwA-t1PUBFtg0M1_SeniorCoordinator_CreativeAssetsandInventory_ZainabIsrar.jpg?auto=format,compres",
      },
      {
        id: "cr11",
        name: "Ifra Inam",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/WQavK0NQ17hcAKhi_IfraInam.jpeg?auto=format,compress",
      },
      {
        id: "cr12",
        name: "Kiana Agarwal",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/YrVa-Cwd6KFMeUqC_KianaAgarwal.jpeg?auto=format,compress",
      },
      {
        id: "cr13",
        name: "Spreha Verma",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/bLV10L2noKj3D3Xo_SprehaVerma.jpg?auto=format,compress",
      },
      {
        id: "cr14",
        name: "Tia Ahuja",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/vScc7XFPR-guHH0S_IMG_4228-TiaAhuja.jpeg?auto=format,compress",
        linkedin: "",
      },
      {
        id: "cr16",
        name: "Pratik Kaduskar",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/3CyskUhvxc8vttpu_image_2026-05-28_013849337-PratikKaduskar.png?auto=format,compress",
        linkedin: "",
      },
      {
        id: "cr17",
        name: "Priyanshi Garg",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/lPCQYNk8kMyAcBnd_IMG_20260528_235217-PriyanshiGarg.jpg?auto=format,compress",
        linkedin: "",
      },
      {
        id: "cr18",
        name: "Vritika Trivedi",
        role: "Team Member",
        photo: "https://images.prismic.io/ieeemuj/hzAXjdzThm8vyNwH_IMG-20260531-WA0001-VaibhavTrivedi.jpg?auto=format,compress",
        linkedin: "",
      },
    ],
  },

  // ── Flying Squad ──────────────────────────────────────────────────────────
  {
    id: "flying-squad",
    label: "Flying Squad",
    members: [
      {
        id: "fs1",
        name: "Anirudh Rawat",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/anirudh-singh-rawat.avif",
        linkedin: "https://www.linkedin.com/in/anirudhsinghrawat1?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: "fs2",
        name: "Swapnil Srivastava",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/swapnil-srivastav.avif",
        linkedin: "https://www.linkedin.com/in/swapnil-srivastav-276292344",
      },
      {
        id: "fs3",
        name: "Garv Sharma",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/garv-sharma.avif",
        linkedin: "https://www.linkedin.com/in/garv-sharma-82685b312?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      },
      {
        id: "fs4",
        name: "Rithik Masand",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fs5",
        name: "Armon Bhuyan",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fs6",
        name: "Arnav Yadav",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fs7",
        name: "Sarthak Malhotra",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/sarthak-malhotra.avif",
        linkedin: "https://www.linkedin.com/in/sarthak-will-work/",
      },
      {
        id: "fs11",
        name: "Medhansh",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/medhansh.avif",
        linkedin: "https://www.linkedin.com/in/medhansh-kapoor-2a7814306?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      },
    ],
  },
];
