import { Team } from "./teamsData";

export const coreData: Team[] = [
  // ── Web Development Team (formerly Technical) ──────────────────────────────
  {
    id: "technical",
    label: "Web Development Team",
    members: [
      {
        id: "tc4",
        name: "Ronit Mahajan",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/ronit-mahajan.avif",
        linkedin: "https://linkedin.com/in/ronit-mahajan",
        github: "",
      },
      {
        id: "tc7",
        name: "Vidhyanshu Kumar",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/vidhyanshu-kumar-cropped-v3-1781885800373.avif",
        linkedin: "https://www.linkedin.com/in/viidhyanshu/",
        github: "",
      },
      {
        id: "tc5",
        name: "Samya Tiwari",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/samya-tiwari.avif",
        linkedin: "https://www.linkedin.com/in/samyaa-tiwarii",
        github: "",
      },
      {
        id: "tc1",
        name: "Devishi Mathur",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/devishi-mathur.avif",
        linkedin: "https://www.linkedin.com/in/devishi-mathur-8380a3210/",
        github: "",
      },
      {
        id: "tc2",
        name: "Divya Srivastava",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/divya-srivastava.avif",
        linkedin: "https://www.linkedin.com/in/divya-srivastava-363b383a0?trk=contact-info",
        github: "",
      },
      {
        id: "tc3",
        name: "Namit Tickoo",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/namit-tickoo.avif",
        linkedin: "https://www.linkedin.com/in/namit-tickoo-69b2a9367?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
        github: "",
      },
      {
        id: "tc8",
        name: "Aakanksha Kumar",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc9",
        name: "Arnav Srivastava",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc10",
        name: "Kavya Choudhary",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc11",
        name: "Kethan Anant",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc12",
        name: "Navya Goel",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc13",
        name: "Tanish Jain",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc14",
        name: "Aparna",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc15",
        name: "Aum Lenka",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc16",
        name: "Shaurya Saxena",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc17",
        name: "Aastha Sood",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc18",
        name: "Disha Bothra",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc19",
        name: "Mukti Dewnani",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc20",
        name: "Shlok Pandey",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc21",
        name: "Tanishq Bhatnagar",
        role: "Team Member",
        photo: null,
        github: "",
      },
    ],
  },

  // ── Graphic Design Team ───────────────────────────────────────────────────
  {
    id: "graphic-design",
    label: "Graphic Design Team",
    members: [
      {
        id: "gd1",
        name: "Aditi Bharadwaj",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/aditi-bhardwaj.avif",
        linkedin: "https://www.linkedin.com/in/aditibhardwaj12",
      },
      {
        id: "gd2",
        name: "Ananya Ghosh",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/ananya-ghosh.avif",
        linkedin: "https://www.linkedin.com/in/ananya-ghosh-a55a7531b/",
      },
      {
        id: "gd3",
        name: "Monishka Kanodia",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/monishka-kanodia.avif",
        linkedin: "https://www.linkedin.com/in/monishka-kanodia-71b757374?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      },
      {
        id: "gd4",
        name: "Nandini Khandelwal",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/nandini-khandelwal.avif",
        linkedin: "https://www.linkedin.com/in/nandinikhandelwal2007",
      },
      {
        id: "gd5",
        name: "Prakhar Raj",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd6",
        name: "Ruhaani Satija",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/ruhaani-satija.avif",
        linkedin: "https://www.linkedin.com/in/ruhaani-satija-044ab0385?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      },
      {
        id: "gd7",
        name: "Soham Prashant More",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/soham-prashant-more.avif",
        linkedin: "https://www.linkedin.com/in/soham-more-muj/",
      },
      {
        id: "gd8",
        name: "Ananya Srivastava",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd9",
        name: "Arunika",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd10",
        name: "Mit Parekh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd11",
        name: "Yuvraaj Dutta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd12",
        name: "Sahil",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd13",
        name: "Shivanshi Punj",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd14",
        name: "Vaani Dhiman",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd15",
        name: "Vidhi Makkar",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd16",
        name: "Maahi Arora",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd17",
        name: "Pranya Gupta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd18",
        name: "Sailendra Sesha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd19",
        name: "Vikram Khambra",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Curations Team ─────────────────────────────────────────────────────────
  {
    id: "curations",
    label: "Curations Team",
    members: [
      {
        id: "cu1",
        name: "Anchal Singh",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/anchal-singh.avif",
        linkedin: "https://www.linkedin.com/in/anchal-singh-",
      },
      {
        id: "cu2",
        name: "Ankush Bhardwaj",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/ankush-bhardwaj.avif",
        linkedin: "https://www.linkedin.com/in/ankush-bhardwaj-b19621283",
      },
      {
        id: "cu3",
        name: "Atharv Vijayvergiya",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/atharv-vijayvergiya.avif",
        linkedin: "http://www.linkedin.com/in/atharv-vijayvergiya-91ab8a370",
      },
      {
        id: "cu4",
        name: "Mishika Sehgal",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/mishika-sehgal.avif",
        linkedin: "https://linkedin.com/in/mishika-sehgal-bb65ab363",
      },
      {
        id: "cu5",
        name: "Sanvi Sinha",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/sanvi-sinha.avif",
        linkedin: "https://www.linkedin.com/in/sanvi-sinha-24b167368/",
      },
      {
        id: "cu6",
        name: "Tejas Kaur",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/tejas-kaur.avif",
        linkedin: "https://www.linkedin.com/in/tejas-kaur-b793ba309/",
      },
      {
        id: "cu7",
        name: "Garvit Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu8",
        name: "Kanishk Punjabi",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu9",
        name: "Parth Gupta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu10",
        name: "Parth Santosh Bharati",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu11",
        name: "Alisha Chaudhary",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu12",
        name: "Nehal Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu13",
        name: "Saurish Mishra",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu14",
        name: "Aarav Goyal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu15",
        name: "Athana Sinha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu16",
        name: "Ayush Gupta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu17",
        name: "Shivansh Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu18",
        name: "Tanishka",
        role: "Team Member",
        photo: null,
      },

    ],
  },

  // ── Social Media Team ──────────────────────────────────────────────────────
  {
    id: "social-media",
    label: "Social Media Team",
    members: [
      {
        id: "sm1",
        name: "Aarohee Bharadwaj",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/aarohee-bharadwaj.avif",
        linkedin: "https://www.linkedin.com/in/aaroheebharadwaj",
      },
      {
        id: "sm2",
        name: "Adrit Das",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/adrit-das.avif",
        linkedin: "https://www.linkedin.com/in/adrit-das-bb5194397?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      },
      {
        id: "sm3",
        name: "Gunjita Saxena",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/gunjita-saxena.avif",
        linkedin: "https://www.linkedin.com/in/gunjita-saxena-60bb17380?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      },
      {
        id: "sm4",
        name: "Naisha Mangla",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/naisha-mangla.avif",
        linkedin: "https://www.linkedin.com/in/naisha-mangla-1aa4a6280?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      },
      {
        id: "sm5",
        name: "Saanvi Lepcha",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/saanvi-lepcha.avif",
        linkedin: "https://www.linkedin.com/in/saanvi-lepcha-4a847a3b6",
      },
      {
        id: "sm6",
        name: "Ankit Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm7",
        name: "Mohd Talha Sufyan",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm8",
        name: "Nileshwari Patil",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm9",
        name: "Snehreet Kaur",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm10",
        name: "Srshti Mehta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm11",
        name: "Suhana Verma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm12",
        name: "Anika Gujral",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm13",
        name: "Divya Sinha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm14",
        name: "Gaadha Amal Nair",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm15",
        name: "Ananya Khanna",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm16",
        name: "Ketan Kumar",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm17",
        name: "Ruchit Kumar Jha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm18",
        name: "Aanya Bharadwaj",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/aanya-bhardwaj.avif",
        linkedin: "https://www.linkedin.com/in/aanya-bhardwaj-a98b4536a?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      },
    ],
  },

  // ── Media & Coverage Team ──────────────────────────────────────────────────
  {
    id: "media",
    label: "Media & Coverage Team",
    members: [
      {
        id: "mc1",
        name: "Aditya Raj",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/aditya-raj.avif",
        linkedin: "https://www.linkedin.com/in/aditya-raj-aa8ab5397",
      },
      {
        id: "mc2",
        name: "Dwijesh Chilukuri",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/dwijesh-chilukuri.avif",
        linkedin: "https://www.linkedin.com/in/dwijesh-chilukuri-803177372?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      },
      {
        id: "mc3",
        name: "Prakhar Gupta",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/prakhar-gupta.avif",
        linkedin: "https://www.linkedin.com/in/prakharrdev",
      },
      {
        id: "mc4",
        name: "Riya Bisht",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/riya-bisht.avif",
        linkedin: "https://www.linkedin.com/in/riyabishtri",
      },
      {
        id: "mc5",
        name: "Hridey Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc6",
        name: "Prakhar Bansal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc7",
        name: "Sanya Varre",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc8",
        name: "Tamanna",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc9",
        name: "Tanishka Panda",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc10",
        name: "Yashika Agarwal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc11",
        name: "Yashu Pandey",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc12",
        name: "Shivi Srivastava",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc13",
        name: "Shubham Doshi",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc14",
        name: "Sugandh Gupta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc15",
        name: "Tirth patel",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Logistics Team ─────────────────────────────────────────────────────────
  {
    id: "logistics",
    label: "Logistics Team",
    members: [
      {
        id: "lo1",
        name: "Bhavya Chavan",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/bhavya.avif",
        linkedin: "https://www.linkedin.com/in/bhavyachavan",
      },
      {
        id: "lo2",
        name: "Daksh Anand",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/daksh-anand.avif",
        linkedin: "https://www.linkedin.com/in/daksh-anand-870895412?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      },
      {
        id: "lo3",
        name: "Shreet Sharma",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/shreet-sharma.avif",
        linkedin: "https://www.linkedin.com/in/ShreetSharma",
      },
      {
        id: "lo4",
        name: "Taran Singh",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/taran-singh.avif",
        linkedin: "https://www.linkedin.com/in/taran-singh-b38a98320?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      },
      {
        id: "lo5",
        name: "Mohit Raj",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/mohit-raj.avif",
        linkedin: "https://www.linkedin.com/in/mohit-raj-006862412",
      },
      {
        id: "lo6",
        name: "Pranjal",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/pranjal.avif",
        linkedin: "https://www.linkedin.com/in/pranjal-muj",
      },
      {
        id: "lo7",
        name: "Ashish Nath Jha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo8",
        name: "Avadhanula Pranav",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo9",
        name: "Harshish Kanoi",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo10",
        name: "Lakshya",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo11",
        name: "Mitul Arora",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo12",
        name: "Saksham Joshi",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo13",
        name: "Shaurya Pathak",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo14",
        name: "Vishwesh Gaidhani",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo15",
        name: "Yuvraj Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo16",
        name: "Arpit Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo17",
        name: "Atharv Garg",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo18",
        name: "Daksh Saxena",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo19",
        name: "Jayaditya De",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo20",
        name: "Keshav Bhatia",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo21",
        name: "Mehul Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo22",
        name: "Padhdar M. Mukeshbhai",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo23",
        name: "Saksham Verma",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Events Team ───────────────────────────────────────────────────────────
  {
    id: "events",
    label: "Events Team",
    members: [
      {
        id: "ev1",
        name: "Aarav Khurana",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/aarav-khurana.avif",
        linkedin: "https://www.linkedin.com/in/aarav-khurana-6b5746373?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
        github: "",
      },
      {
        id: "ev2",
        name: "Abir Harne",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/abir-harne.avif",
        linkedin: "https://www.linkedin.com/in/abirharne",
      },
      {
        id: "ev3",
        name: "Aditi Rai",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/aditi-rai.avif",
        linkedin: "https://www.linkedin.com/in/aditi-rai-801832378/",
      },
      {
        id: "ev4",
        name: "Amisha Upadhyay",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/amisha-upadhyay.avif",
        linkedin: "https://www.linkedin.com/in/amisha-upadhyay-402796378?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      },
      {
        id: "ev5",
        name: "Ananya Mishra",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/ananya-mishra.avif",
        linkedin: "https://www.linkedin.com/in/ananya-mishra-87930a3a3/",
      },
      {
        id: "ev6",
        name: "Anukriti Verma",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/anukriti-verma.avif",
        linkedin: "https://www.linkedin.com/in/anukriti-verma-b3177a376/",
      },
      {
        id: "ev7",
        name: "Harshvardhan Khaitan",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/harshvardhan-khaitan.avif",
        linkedin: "https://www.linkedin.com/in/harshvardhankh",
      },
      {
        id: "ev8",
        name: "Krishna Kakkar",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev9",
        name: "Pari Ahuja",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/pari-ahuja.avif",
        linkedin: "https://www.linkedin.com/in/pari-ahuja-3550bb368",
      },
      {
        id: "ev10",
        name: "Prisha Mittal",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/prisha-mittal.avif",
        linkedin: "https://www.linkedin.com/in/prisha-mittal-561a33382?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      },
      {
        id: "ev11",
        name: "Shreyansh Sharma",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/shreyansh-sharma.avif",
        linkedin: "https://www.linkedin.com/in/shreyansh-sharma-97244726a/",
      },
      {
        id: "ev12",
        name: "Shriya Raizada",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/shriya-raizada.avif",
        linkedin: "http://linkedin.com/in/shriya-raizada-3b1420320",
      },
      {
        id: "ev13",
        name: "Agrim Tripathi",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev14",
        name: "Aryan Wondraw",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev15",
        name: "Kyna Sehgal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev16",
        name: "Gargi Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev17",
        name: "Nishika Jain",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev18",
        name: "Pradyumna Raj Chaudhary",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev19",
        name: "Mehek Marwaha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev20",
        name: "Mohisha Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev21",
        name: "Nandini Bali",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev22",
        name: "Sahaj Bhattia",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev23",
        name: "Aditi Agarwal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev24",
        name: "Akshita Sinha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev25",
        name: "Ananya Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev26",
        name: "Krishna Tripathi",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev27",
        name: "Mahi Mehrotra",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev28",
        name: "Manya Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev29",
        name: "Niharika Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev30",
        name: "Aparna Anand",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev31",
        name: "Daksh Agarwal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev32",
        name: "Prannoy Sen",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev33",
        name: "Shreyansh Sinha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev34",
        name: "Sounarda Mondal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev35",
        name: "Swastika Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev36",
        name: "Tia Anuja",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev37",
        name: "Yash Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev38",
        name: "Yuvraj Sethi",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Marketing Team ────────────────────────────────────────────────────────
  {
    id: "marketing",
    label: "Marketing Team",
    members: [
      {
        id: "mk1",
        name: "Anvi Goyal",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/anvi-goyal.avif",
        linkedin: "https://www.linkedin.com/in/anvi-goyal-14796640b?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      },
      {
        id: "mk2",
        name: "Daksh",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/daksh.avif",
        linkedin: "",
      },
      {
        id: "mk3",
        name: "Dhruv Talwar",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/dhruv-talwar.avif",
        linkedin: "https://www.linkedin.com/in/dhruv-talwar-4015872a1",
      },
      {
        id: "mk4",
        name: "Eva Singh",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/eva.avif",
        linkedin: "https://www.linkedin.com/in/eva-singh-96852a29b/",
      },
      {
        id: "mk5",
        name: "Kashvi Mohta",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/kashvi-mohta.avif",
        linkedin: "https://www.linkedin.com/in/kashvi-mohta-73a516378",
      },
      {
        id: "mk6",
        name: "Shresht Gulati",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/shresth-gulati.avif",
        linkedin: "https://www.linkedin.com/in/shresth-gulati-00a029333?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      },
      {
        id: "mk7",
        name: "Srishti Suman Gupta",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/srishti-suman-gupta.avif",
        linkedin: "https://www.linkedin.com/in/srishti-suman-g-820005383?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      },
      {
        id: "mk8",
        name: "Yuvika Sachdeva",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/yuvika-sachdeva.avif",
        linkedin: "https://www.linkedin.com/in/yuvika-sachdeva-82a391295?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      },
      {
        id: "mk9",
        name: "Adit Tandon",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk10",
        name: "Akshadha Gupta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk11",
        name: "Alisha Yadav",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk12",
        name: "Anshul Pandey",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk13",
        name: "Arnav Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk14",
        name: "Shriya Stuti",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk15",
        name: "Shriya Stutt",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk16",
        name: "Trishala Ojha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk17",
        name: "Abhigyan Padhy",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk18",
        name: "Abhishek Vishnoi",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk19",
        name: "Prarthana Agarwal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk20",
        name: "Shouryam Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk21",
        name: "Tanisha Salian",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk22",
        name: "Akansha Banerjee",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk23",
        name: "Arnav Meher",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk24",
        name: "Diwansh Khowala",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk25",
        name: "Priyanshu",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Corporate Team ────────────────────────────────────────────────────────
  {
    id: "corporate",
    label: "Corporate Team",
    members: [
      {
        id: "cp1",
        name: "Armaan Kashyap",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/armaan-kashyap.avif",
        linkedin: "https://www.linkedin.com/in/armaan-kashyap-46a594371",
      },
      {
        id: "cp2",
        name: "Daksh Narwaria",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/daksh-narwaria.avif",
        linkedin: "https://www.linkedin.com/in/dakshnarwaria?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      },
      {
        id: "cp3",
        name: "Divya Surve",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/divya-surve.avif",
        linkedin: "https://www.linkedin.com/in/divya-surve-30797036b/",
      },
      {
        id: "cp4",
        name: "Krish Barnwal",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/krish-barnwal.avif",
        linkedin: "https://www.linkedin.com/in/krish-b-2b33b829a?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      },
      {
        id: "cp5",
        name: "Shana Srivastava",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/shana-srivastava.avif",
        linkedin: "https://www.linkedin.com/in/shana-srivastava-489a81366",
      },
      {
        id: "cp6",
        name: "Sweera Anand",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/sweera-anand.avif",
        linkedin: "",
      },
      {
        id: "cp7",
        name: "Amishi kingrani",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp8",
        name: "Atharva Awasthy",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp9",
        name: "Danish Mandalapu",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp10",
        name: "Harsh Wardhan",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp11",
        name: "Manasvi Karthik",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp12",
        name: "Neeyati Agrawal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp13",
        name: "Srisha Jha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp14",
        name: "Aanya Singhal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp15",
        name: "Saisha Narang",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp16",
        name: "Vaibhav Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp17",
        name: "Yash Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp18",
        name: "Akshita Rohilla",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp19",
        name: "Daksh",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/daksh.avif",
        linkedin: "",
      },
      {
        id: "cp20",
        name: "Jivaansh Chandna",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp21",
        name: "Shobham S. Panigarhy",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp22",
        name: "Vanshika Tyagi",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Hospitality Team ───────────────────────────────────────────────────────
  {
    id: "hospitality",
    label: "Hospitality Team",
    members: [
      {
        id: "ho1",
        name: "Arnav Khanna",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/arnav-khanna.avif",
        linkedin: "https://www.linkedin.com/in/arnav-khanna-655113381",
      },
      {
        id: "ho2",
        name: "Chaitanya Bharadwaj",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/chaitanya-bhardwaj.avif",
        linkedin: "https://www.linkedin.com/in/chaitanya-bhardwaj-1a1a81372/",
      },
      {
        id: "ho3",
        name: "Sanat Gupta",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/sanat-gupta.avif",
        linkedin: "https://www.linkedin.com/in/sanat-g-b51701249",
      },
      {
        id: "ho4",
        name: "Saanvi Mittal",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/saanvi-mittal.avif",
        linkedin: "https://www.linkedin.com/in/saanvi-m-362905353?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
      },
      {
        id: "ho5",
        name: "Anshika Nagar",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho6",
        name: "Devangini",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho7",
        name: "Heet Bhatt",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho8",
        name: "Tushi Choudhary",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho9",
        name: "Arnav Asrani",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho10",
        name: "Naman Saini",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho11",
        name: "Ritesh Soni",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho12",
        name: "Aashi Gupta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho13",
        name: "Harsh Deep Ratna",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho14",
        name: "Prachi",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho15",
        name: "Veerottam K. Kulshrestha",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Content Team ──────────────────────────────────────────────────────────
  {
    id: "content",
    label: "Content Team",
    members: [
      {
        id: "co1",
        name: "Akshay Pathak",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/akshay-pathak.avif",
        linkedin: "https://www.linkedin.com/in/akshay-pathak-b72576362?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      },
      {
        id: "co2",
        name: "Devika Beri",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/devika-beri.avif",
        linkedin: "https://www.linkedin.com/in/devika-beri-",
      },
      {
        id: "co3",
        name: "Mehr Mehta",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/mehr-mehta.avif",
        linkedin: "https://www.linkedin.com/in/mehr-mehta-986598376?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
      },
      {
        id: "co4",
        name: "Rian Anand",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/rian-anand.avif",
        linkedin: "https://www.linkedin.com/in/riananand",
      },
      {
        id: "co5",
        name: "Rishita Malik",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/rishita-malik.avif",
        linkedin: "https://www.linkedin.com/in/rishita-malik-91005136b",
      },
      {
        id: "co6",
        name: "Geetika Khatri",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co7",
        name: "Ipshita",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co8",
        name: "Lavisna Rohra",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co9",
        name: "Ananya Kedia",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co10",
        name: "Andrea Dia Benjamin",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co11",
        name: "Kavya Das",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co12",
        name: "Akshita Shah",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co13",
        name: "Anushka Soni",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co14",
        name: "Saloni Sinha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co15",
        name: "Vaibhav Verma",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Finance Team ──────────────────────────────────────────────────────────
  {
    id: "finance",
    label: "Finance Team",
    members: [
      {
        id: "fi1",
        name: "Anshul Sawhney",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/anshul-sawhney.avif",
        linkedin: "https://www.linkedin.com/in/anshul-sawhney-280263370?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      },
      {
        id: "fi2",
        name: "Likisha Grover",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/likisha.avif",
        linkedin: "https://www.linkedin.com/in/likisha-grover-b602ab379/",
      },
      {
        id: "fi3",
        name: "Tarush Prasad",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/tarush-prasad.avif",
        linkedin: "https://www.linkedin.com/in/tarush-prasad-834b64380/",
      },
      {
        id: "fi4",
        name: "Navya Khurana",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi5",
        name: "Riddhi Gupta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi6",
        name: "Suyash K. Kshitij",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi7",
        name: "Dhruv Sahrawat",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi8",
        name: "Jannat Ghuman",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi9",
        name: "Raima",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi10",
        name: "Mansi Thakre",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi11",
        name: "Rachit Goyal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi12",
        name: "Suryansh Thakur",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi13",
        name: "Tansukh",
        role: "Team Member",
        photo: null,
      },
    ],
  },
    // ── Crafts Team ───────────────────────────────────────────────────────────
  {
    id: "crafts",
    label: "Crafts Team",
    members: [
      {
        id: "cr1",
        name: "Aarushi Gupta",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/aarushi-gupta.avif",
        linkedin: "https://www.linkedin.com/in/aarushi-gupta",
      },
      {
        id: "cr2",
        name: "Aashie Singh",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/aashie-singh.avif",
        linkedin: "https://www.linkedin.com/in/aashie-singh-50393237b?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      },
      {
        id: "cr3",
        name: "Akshita Dhiman",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/akshita-dhiman.avif",
        linkedin: "https://www.linkedin.com/in/akshita-dhiman-29630a343",
      },
      {
        id: "cr4",
        name: "Maya Jakhad",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/maya-jakhad.avif",
        linkedin: "https://www.linkedin.com/in/maya-jakhad-43a459379?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      },
      {
        id: "cr5",
        name: "Radhika Bansal",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/radhika.avif",
        linkedin: "https://www.linkedin.com/in/radhika-bansal-3b4849412",
      },
      {
        id: "cr6",
        name: "Anhad Ansari",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr7",
        name: "Ayaan Khan",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr8",
        name: "Kashvi Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr9",
        name: "Shubh Vats",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr10",
        name: "Zainab Israr",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr11",
        name: "Ifra Inam",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr12",
        name: "Kiana Agarwal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr13",
        name: "Spreha Verma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr14",
        name: "Tia Ahuja",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr15",
        name: "Ansh Gupta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr16",
        name: "Pratik Kaduskar",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr17",
        name: "Priyanshi Garg",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr18",
        name: "Vritika Trivedi",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Flying Squad ──────────────────────────────────────────────────────────
  {
    id: "flying-squad",
    label: "Flying Squad",
    members: [
      {
        id: "fs1",
        name: "Anirudh Rawat",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/anirudh-singh-rawat.avif",
        linkedin: "https://www.linkedin.com/in/anirudhsinghrawat1?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: "fs2",
        name: "Swapnil Srivastava",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/swapnil-srivastav.avif",
        linkedin: "https://www.linkedin.com/in/swapnil-srivastav-276292344",
      },
      {
        id: "fs3",
        name: "Garv Sharma",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/garv-sharma.avif",
        linkedin: "https://www.linkedin.com/in/garv-sharma-82685b312?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      },
      {
        id: "fs4",
        name: "Rithik Masand",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fs5",
        name: "Armon Bhuyan",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fs6",
        name: "Arnav Yadav",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fs7",
        name: "Sarthak Malhotra",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/sarthak-malhotra.avif",
        linkedin: "https://www.linkedin.com/in/sarthak-will-work/",
      },
      {
        id: "fs8",
        name: "Akshit Katare",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fs9",
        name: "Devang Garg",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fs10",
        name: "Prakhar Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fs11",
        name: "Medhansh",
        role: "Team Member",
        photo: "https://pub-2b91df05320148438318902a8dc7795b.r2.dev/team-photos/medhansh.avif",
        linkedin: "https://www.linkedin.com/in/medhansh-kapoor-2a7814306?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      },

    ],
  },
];
