import { Team } from "./teamsData";

export const executiveData: Team[] = [
  // ── Convenors ──────────────────────────────────────────────────────────────
{
  id: "conveners",
  label: "CONVENERS",
  members: [
    {
      id: "cv1",
      name: "Tanmoy Mandal",
      role: "Convener",
      photo: "https://images.prismic.io/ieeemuj/aLjIZGGNHVfTOoNW_TanmoyMondal-technicalHackX3.0.jpg?auto=format,compress",
    },
    {
      id: "cv2",
      name: "Arunanshu Basu",
      role: "Convener",
      photo: null,
    },
    {
      id: "cv3",
      name: "Palakshi Sirsat",
      role: "Convener",
      photo: null,
    },
    {
      id: "cv4",
      name: "Shubhanshu Dixit",
      role: "Convener",
      photo: "https://images.prismic.io/ieeemuj/YeEGqiXTiDFTi97v_Shubhanshu.jpeg?auto=format,compress",
    },
  ],
},

// ── Directors ────────────────────────────────────────────────────────────────
{
  id: "directors",
  label: "DIRECTORS",
  members: [
    {
      id: "dr1",
      name: "Aarush Dayal",
      role: "Director",
      photo: "https://images.prismic.io/ieeemuj/aLjFWGGNHVfTOoEZ_AarushDayal-operations-HackX3.0.jpg?auto=format,compress",
    },
    {
      id: "dr2",
      name: "Keshav Anand",
      role: "Director",
      photo: "https://images.prismic.io/ieeemuj/aD_vnLh8WN-LVkZP_96ad7182-9dd4-46bc-8a16-9f3a61cb9b04-KeshavAnand.jpeg?auto=format,compress",
    },
    {
      id: "dr3",
      name: "Sara Pansuriya",
      role: "Director",
      photo: "https://images.prismic.io/ieeemuj/aLjG7WGNHVfTOoJZ_SaraPansuriya-Marketing-HackX3.0.jpeg?auto=format,compress",
    },
    {
      id: "dr4",
      name: "Dolly Srivastava",
      role: "Director",
      photo: "https://images.prismic.io/ieeemuj/aD3a2rh8WN-LVfjA_wowkyaphotohai-DollySrivastava.jpg?auto=format,compress",
    },
    {
      id: "dr5",
      name: "Shreya Daljeet",
      role: "Director",
      photo: "https://images.prismic.io/ieeemuj/aLjCymGNHVfTOn9g_ShreyaDaljeet-content-HackX3.0.png?auto=format,compress",
    },
    {
      id: "dr6",
      name: "Anshuman Singh",
      role: "Director",
      photo: "https://images.prismic.io/ieeemuj/aEM3B7h8WN-LVxqu_20250405_211338-AnshumanSingh.jpg?auto=format,compress",
    },
    {
      id: "dr7",
      name: "Pratyush Sharma",
      role: "Director",
      photo: null,
    },
    {
      id: "dr8",
      name: "Yatharth Rajpoot",
      role: "Director",
      photo: null,
    },
    {
      id: "dr9",
      name: "Aadrit Kaushik",
      role: "Director",
      photo: null,
    },
    {
      id: "dr10",
      name: "Anushka Srivastav",
      role: "Director",
      photo: null,
    },
    {
      id: "dr11",
      name: "Navya Bhardwaj",
      role: "Director",
      photo: null,
    },
    {
      id: "dr12",
      name: "Shrinivas Kharpade",
      role: "Director",
      photo: null,
    },
    {
      id: "dr13",
      name: "Kshiti Singh",
      role: "Director",
      photo: null,
    },
    {
      id: "dr14",
      name: "Akshat Raheja",
      role: "Director",
      photo: null,
    },
    {
      id: "dr15",
      name: "Ashita Saxena",
      role: "Director",
      photo: null,
    },
    {
      id: "dr16",
      name: "Shivangi Kotnala",
      role: "Director",
      photo: null,
    },
    {
      id: "dr17",
      name: "Sarath Mohanraj",
      role: "Director",
      photo: null,
    },
    {
      id: "dr18",
      name: "Vaibhav Kumar",
      role: "Director",
      photo: null,
    },
    {
      id: "dr19",
      name: "Rishan Mazumdar",
      role: "Director",
      photo: "https://images.prismic.io/ieeemuj/qlFwXpTB2igF5gPT_rishaan.jpeg?auto=format,compress",
    },
    {
      id: "dr20",
      name: "Harsh Raj",
      role: "Director",
      photo: "https://images.prismic.io/ieeemuj/jCS6N4_zzUmgQ9J3_harshraj.jpeg?auto=format,compress",
    },
    {
      id: "dr21",
      name: "Garv Sharma",
      role: "Director",
      photo: "https://images.prismic.io/ieeemuj/0-vKe0C1aqOXFccJ_garv.jpeg?auto=format,compress",
    },
    {
      id: "dr22",
      name: "Pranav Kheole",
      role: "Director",
      photo: "https://images.prismic.io/ieeemuj/_j2XV9wttcn6LykD_Pranav.jpeg?auto=format,compress",
    },
    {
      id: "dr23",
      name: "Yash Raj",
      role: "Director",
      photo: "https://images.prismic.io/ieeemuj/4JzML6VE38ckDP8H_Yash.jpg?auto=format,compress",
    },
    {
      id: "dr24",
      name: "Manya Moonat",
      role: "Director",
      photo: "https://images.prismic.io/ieeemuj/jaAvTBvqNqvYnauY_Maanya.jpg?auto=format,compress",
    },
  ],
},
{
  id: "technical_mentors",
  label: "TECHNICAL MENTORS",
  members: [
    {
      id: "tm1",
      name: "Yogesh Jajoria",
      role: "Mentor",
      photo: null,
    },
    {
      id: "tm2",
      name: "Manan Chaudhary",
      role: "Mentor",
      photo: null,
    },
  ],
},
{
  id: "team_heads",
  label: "Team Heads",
  members: [
    {
      id: "th1",
      name: "Aarush Dayal",
      role: "Events Head",
      photo: "https://images.prismic.io/ieeemuj/aLjFWGGNHVfTOoEZ_AarushDayal-operations-HackX3.0.jpg?auto=format,compress",
    },
    {
      id: "th2",
      name: "Shreya Daljeet",
      role: "Events Head",
      photo: "https://images.prismic.io/ieeemuj/aLjCymGNHVfTOn9g_ShreyaDaljeet-content-HackX3.0.png?auto=format,compress",
    },
    {
      id: "th3",
      name: "Anushka Srivastav",
      role: "Events Head",
      photo: null,
    },
    {
      id: "th4",
      name: "Aadrit Kaushik",
      role: "Events Head",
      photo: null,
    },
    {
      id: "th5",
      name: "Palakshi Sirsat",
      role: "Events Head",
      photo: null,
    },
    {
      id: "th6",
      name: "Kshiti Singh",
      role: "Events Head",
      photo: null,
    },
    {
      id: "th7",
      name: "Manya Moonat",
      role: "Events Head",
      photo: "https://images.prismic.io/ieeemuj/jaAvTBvqNqvYnauY_Maanya.jpg?auto=format,compress",
    },
    {
      id: "th8",
      name: "Yash Raj",
      role: "Events Head",
      photo: "https://images.prismic.io/ieeemuj/4JzML6VE38ckDP8H_Yash.jpg?auto=format,compress",
    },

    {
      id: "th9",
      name: "Tanmoy Mandal",
      role: "Marketing Head",
      photo: "https://images.prismic.io/ieeemuj/aLjIZGGNHVfTOoNW_TanmoyMondal-technicalHackX3.0.jpg?auto=format,compress",
    },
    {
      id: "th10",
      name: "Sara Pansuriya",
      role: "Marketing Head",
      photo: "https://images.prismic.io/ieeemuj/aLjG7WGNHVfTOoJZ_SaraPansuriya-Marketing-HackX3.0.jpeg?auto=format,compress",
    },
    {
      id: "th11",
      name: "Arunanshu Basu",
      role: "Marketing Head",
      photo: null,
    },
    {
      id: "th12",
      name: "Navya Bhardwaj",
      role: "Marketing Head",
      photo: null,
    },
    {
      id: "th13",
      name: "Palakshi Sirsat",
      role: "Marketing Head",
      photo: null,
    },
    {
      id: "th14",
      name: "Pranav Kheole",
      role: "Marketing Head",
      photo: "https://images.prismic.io/ieeemuj/_j2XV9wttcn6LykD_Pranav.jpeg?auto=format,compress",
    },
    {
      id: "th15",
      name: "Manya Moonat",
      role: "Marketing Head",
      photo: "https://images.prismic.io/ieeemuj/jaAvTBvqNqvYnauY_Maanya.jpg?auto=format,compress",
    },

    {
      id: "th16",
      name: "Tanmoy Mandal",
      role: "Corporate Head",
      photo: "https://images.prismic.io/ieeemuj/aLjIZGGNHVfTOoNW_TanmoyMondal-technicalHackX3.0.jpg?auto=format,compress",
    },
    {
      id: "th17",
      name: "Dolly Srivastava",
      role: "Corporate Head",
      photo: "https://images.prismic.io/ieeemuj/aD3a2rh8WN-LVfjA_wowkyaphotohai-DollySrivastava.jpg?auto=format,compress",
    },
    {
      id: "th18",
      name: "Aadrit Kaushik",
      role: "Corporate Head",
      photo: null,
    },
    {
      id: "th19",
      name: "Navya Bhardwaj",
      role: "Corporate Head",
      photo: null,
    },
    {
      id: "th20",
      name: "Sarath Mohanraj",
      role: "Corporate Head",
      photo: null,
    },
    {
      id: "th21",
      name: "Shivangi Kotnala",
      role: "Corporate Head",
      photo: null,
    },
    {
      id: "th22",
      name: "Garv Sharma",
      role: "Corporate Head",
      photo: "https://images.prismic.io/ieeemuj/0-vKe0C1aqOXFccJ_garv.jpeg?auto=format,compress",
    },
    {
      id: "th23",
      name: "Yash Raj",
      role: "Corporate Head",
      photo: "https://images.prismic.io/ieeemuj/4JzML6VE38ckDP8H_Yash.jpg?auto=format,compress",
    },

    {
      id: "th24",
      name: "Aarush Dayal",
      role: "Graphic Design Head",
      photo: "https://images.prismic.io/ieeemuj/aLjFWGGNHVfTOoEZ_AarushDayal-operations-HackX3.0.jpg?auto=format,compress",
    },
    {
      id: "th25",
      name: "Pratyush Sharma",
      role: "Graphic Design Head",
      photo: null,
    },
    {
      id: "th26",
      name: "Akshat Raheja",
      role: "Graphic Design Head",
      photo: null,
    },
    {
      id: "th27",
      name: "Garv Sharma",
      role: "Graphic Design Head",
      photo: "https://images.prismic.io/ieeemuj/0-vKe0C1aqOXFccJ_garv.jpeg?auto=format,compress",
    },

    {
      id: "th28",
      name: "Tanmoy Mandal",
      role: "Technical Head",
      photo: "https://images.prismic.io/ieeemuj/aLjIZGGNHVfTOoNW_TanmoyMondal-technicalHackX3.0.jpg?auto=format,compress",
    },
    {
      id: "th29",
      name: "Manan Chaudhary",
      role: "Technical Head",
      photo: null,
    },
    {
      id: "th30",
      name: "Yogesh Jajoria",
      role: "Technical Head",
      photo: null,
    },
    {
      id: "th31",
      name: "Vaibhav Kumar",
      role: "Technical Head",
      photo: null,
    },
    {
      id: "th32",
      name: "Harsh Raj",
      role: "Technical Head",
      photo: "https://images.prismic.io/ieeemuj/jCS6N4_zzUmgQ9J3_harshraj.jpeg?auto=format,compress",
    },
    {
      id: "th33",
      name: "Yash Raj",
      role: "Technical Head",
      photo: "https://images.prismic.io/ieeemuj/4JzML6VE38ckDP8H_Yash.jpg?auto=format,compress",
    },

    {
      id: "th34",
      name: "Sara Pansuriya",
      role: "Content Head",
      photo: "https://images.prismic.io/ieeemuj/aLjG7WGNHVfTOoJZ_SaraPansuriya-Marketing-HackX3.0.jpeg?auto=format,compress",
    },
    {
      id: "th35",
      name: "Anushka Srivastav",
      role: "Content Head",
      photo: null,
    },
    {
      id: "th36",
      name: "Ashita Saxena",
      role: "Content Head",
      photo: null,
    },
    {
      id: "th37",
      name: "Manya Moonat",
      role: "Content Head",
      photo: "https://images.prismic.io/ieeemuj/jaAvTBvqNqvYnauY_Maanya.jpg?auto=format,compress",
    },

    {
      id: "th38",
      name: "Anshuman Singh",
      role: "Media & Coverage Head",
      photo: "https://images.prismic.io/ieeemuj/aEM3B7h8WN-LVxqu_20250405_211338-AnshumanSingh.jpg?auto=format,compress",
    },
    {
      id: "th39",
      name: "Shrinivas Kharpade",
      role: "Media & Coverage Head",
      photo: null,
    },
    {
      id: "th40",
      name: "Vaibhav Kumar",
      role: "Media & Coverage Head",
      photo: null,
    },
    {
      id: "th41",
      name: "Pranav Kheole",
      role: "Media & Coverage Head",
      photo: "https://images.prismic.io/ieeemuj/_j2XV9wttcn6LykD_Pranav.jpeg?auto=format,compress",
    },

    {
      id: "th42",
      name: "Dolly Srivastava",
      role: "Curations Head",
      photo: "https://images.prismic.io/ieeemuj/aD3a2rh8WN-LVfjA_wowkyaphotohai-DollySrivastava.jpg?auto=format,compress",
    },
    {
      id: "th43",
      name: "Yatharth Rajpoot",
      role: "Curations Head",
      photo: null,
    },
    {
      id: "th44",
      name: "Ashita Saxena",
      role: "Curations Head",
      photo: null,
    },
    {
      id: "th45",
      name: "Sarath Mohanraj",
      role: "Curations Head",
      photo: null,
    },
    {
      id: "th46",
      name: "Shubhanshu Dixit",
      role: "Curations Head",
      photo: "https://images.prismic.io/ieeemuj/YeEGqiXTiDFTi97v_Shubhanshu.jpeg?auto=format,compress",
    },

    {
      id: "th47",
      name: "Keshav Anand",
      role: "Logistics Head",
      photo: "https://images.prismic.io/ieeemuj/aD_vnLh8WN-LVkZP_96ad7182-9dd4-46bc-8a16-9f3a61cb9b04-KeshavAnand.jpeg?auto=format,compress",
    },
    {
      id: "th48",
      name: "Anshuman Singh",
      role: "Logistics Head",
      photo: "https://images.prismic.io/ieeemuj/aEM3B7h8WN-LVxqu_20250405_211338-AnshumanSingh.jpg?auto=format,compress",
    },
    {
      id: "th49",
      name: "Arunanshu Basu",
      role: "Logistics Head",
      photo: null,
    },
    {
      id: "th50",
      name: "Pratyush Sharma",
      role: "Logistics Head",
      photo: null,
    },
    {
      id: "th51",
      name: "Akshat Raheja",
      role: "Logistics Head",
      photo: null,
    },
    {
      id: "th52",
      name: "Rishan Mazumdar",
      role: "Logistics Head",
      photo: "https://images.prismic.io/ieeemuj/qlFwXpTB2igF5gPT_rishaan.jpeg?auto=format,compress",
    },

    {
      id: "th53",
      name: "Keshav Anand",
      role: "Hospitality Head",
      photo: "https://images.prismic.io/ieeemuj/aD_vnLh8WN-LVkZP_96ad7182-9dd4-46bc-8a16-9f3a61cb9b04-KeshavAnand.jpeg?auto=format,compress",
    },
    {
      id: "th54",
      name: "Anshuman Singh",
      role: "Hospitality Head",
      photo: "https://images.prismic.io/ieeemuj/aEM3B7h8WN-LVxqu_20250405_211338-AnshumanSingh.jpg?auto=format,compress",
    },
    {
      id: "th55",
      name: "Arunanshu Basu",
      role: "Hospitality Head",
      photo: null,
    },
    {
      id: "th56",
      name: "Pratyush Sharma",
      role: "Hospitality Head",
      photo: null,
    },
    {
      id: "th57",
      name: "Kshiti Singh",
      role: "Hospitality Head",
      photo: null,
    },
    {
      id: "th58",
      name: "Garv Sharma",
      role: "Hospitality Head",
      photo: "https://images.prismic.io/ieeemuj/0-vKe0C1aqOXFccJ_garv.jpeg?auto=format,compress",
    },
    {
      id: "th59",
      name: "Rishan Mazumdar",
      role: "Hospitality Head",
      photo: "https://images.prismic.io/ieeemuj/qlFwXpTB2igF5gPT_rishaan.jpeg?auto=format,compress",
    },

    {
      id: "th60",
      name: "Dolly Srivastava",
      role: "Finance Head",
      photo: "https://images.prismic.io/ieeemuj/aD3a2rh8WN-LVfjA_wowkyaphotohai-DollySrivastava.jpg?auto=format,compress",
    },
    {
      id: "th61",
      name: "Aadrit Kaushik",
      role: "Finance Head",
      photo: null,
    },
    {
      id: "th62",
      name: "Sarath Mohanraj",
      role: "Finance Head",
      photo: null,
    },
    {
      id: "th63",
      name: "Harsh Raj",
      role: "Finance Head",
      photo: "https://images.prismic.io/ieeemuj/jCS6N4_zzUmgQ9J3_harshraj.jpeg?auto=format,compress",
    },

    {
      id: "th64",
      name: "Shreya Daljeet",
      role: "Social Media Head",
      photo: "https://images.prismic.io/ieeemuj/aLjCymGNHVfTOn9g_ShreyaDaljeet-content-HackX3.0.png?auto=format,compress",
    },
    {
      id: "th65",
      name: "Aadrit Kaushik",
      role: "Social Media Head",
      photo: null,
    },
    {
      id: "th66",
      name: "Shrinivas Kharpade",
      role: "Social Media Head",
      photo: null,
    },
    {
      id: "th67",
      name: "Shivangi Kotnala",
      role: "Social Media Head",
      photo: null,
    },
    {
      id: "th68",
      name: "Shubhanshu Dixit",
      role: "Social Media Head",
      photo: "https://images.prismic.io/ieeemuj/YeEGqiXTiDFTi97v_Shubhanshu.jpeg?auto=format,compress",
    },
    {
      id: "th69",
      name: "Pranav Kheole",
      role: "Social Media Head",
      photo: "https://images.prismic.io/ieeemuj/_j2XV9wttcn6LykD_Pranav.jpeg?auto=format,compress",
    },

    {
      id: "th70",
      name: "Sara Pansuriya",
      role: "Crafts Head",
      photo: "https://images.prismic.io/ieeemuj/aLjG7WGNHVfTOoJZ_SaraPansuriya-Marketing-HackX3.0.jpeg?auto=format,compress",
    },
    {
      id: "th71",
      name: "Yatharth Rajpoot",
      role: "Crafts Head",
      photo: null,
    },
    {
      id: "th72",
      name: "Akshat Raheja",
      role: "Crafts Head",
      photo: null,
    },
    {
      id: "th73",
      name: "Shubhanshu Dixit",
      role: "Crafts Head",
      photo: "https://images.prismic.io/ieeemuj/YeEGqiXTiDFTi97v_Shubhanshu.jpeg?auto=format,compress",
    },

    {
      id: "th74",
      name: "Keshav Anand",
      role: "Flying Squad Head",
      photo: "https://images.prismic.io/ieeemuj/aD_vnLh8WN-LVkZP_96ad7182-9dd4-46bc-8a16-9f3a61cb9b04-KeshavAnand.jpeg?auto=format,compress",
    },
    {
      id: "th75",
      name: "Arunanshu Basu",
      role: "Flying Squad Head",
      photo: null,
    },
    {
      id: "th76",
      name: "Pratyush Sharma",
      role: "Flying Squad Head",
      photo: null,
    },
    {
      id: "th77",
      name: "Akshat Raheja",
      role: "Flying Squad Head",
      photo: null,
    },
    {
      id: "th78",
      name: "Rishan Mazumdar",
      role: "Flying Squad Head",
      photo: "https://images.prismic.io/ieeemuj/qlFwXpTB2igF5gPT_rishaan.jpeg?auto=format,compress",
    },
  ],
},
];
